"""
Algorithms for solving the Coupled Differential System.

Given a differential field k and f1, f2, g1, g2 in k, the coupled
differential system problem is to decide whether the system

    Dy1 + f1*y1 - f2*y2 == g1
    Dy2 + f2*y1 + f1*y2 == g2

has a solution (y1, y2) in k x k, and to find one if there are some.
Writing y == y1 + y2*sqrt(-1), the system is exactly the real and
imaginary parts of the Risch differential equation

    Dy + (f1 + f2*sqrt(-1))*y == g1 + g2*sqrt(-1)

over k(sqrt(-1)), where D is extended by D(sqrt(-1)) == 0.  Coupled
systems are only generated by the integration algorithm when
sqrt(-1) is not in k (they arise from the hypertangent case, Sections
5.10 and 6.6), so the equivalence goes both ways and
coupled_DE_system() solves the system through the equivalent Risch
differential equation.

For k == k0(t) with t a monomial over k0, Bronstein's Chapter 8 also
gives direct algorithms for the cancellation cases of the Risch
differential equation which recurse into coupled systems over k0
instead of Risch differential equations over k0(sqrt(-1)):
coupled_DE_cancel_prim() (Section 8.1), coupled_DE_cancel_exp()
(Section 8.2), and coupled_DE_cancel_tan() (Section 8.4); Section 8.3
(nonlinear monomials) has no general algorithm, just as in the Risch
differential equation case.

The code in this module is a specialization of Chapter 8 to
a == -1: the book states Sections 8.1 and 8.2 for a general constant
a with sqrt(a) not in k(t), but the integration algorithm only ever
generates a == -1, and the hypertangent case of Section 8.4 requires
it.
"""
from __future__ import annotations

from sympy.core.numbers import I, oo
from sympy.polys.polymatrix import PolyMatrix as Matrix
from sympy.polys.polytools import Poly, cancel

from .prde import (is_deriv_in_field, is_log_deriv_k_t_radical_in_field,
    parametric_log_deriv, param_rischDE, real_imag)
from .rde import rischDE
from .risch import (DecrementLevel, NonElementaryIntegralException,
    derivation, frac_in)


def conjugate_expr(e):
    """
    The complex conjugate of ``e``, an expression whose only nonreal
    subexpression is an explicit ``I``.

    Explanation
    ===========

    Elements of the differential fields handled by this module are
    real (sqrt(-1) is not in k(t)), so an element of k(sqrt(-1)) is
    conjugated by substituting ``I -> -I``; no other subexpression is
    touched, unlike conjugate(), which would introduce conjugate()
    objects around the symbols.
    """
    return e.subs(I, -I)


def real_imag_expr(e):
    """
    The real and imaginary parts of ``e``, an expression whose only
    nonreal subexpression is an explicit ``I``.

    Explanation
    ===========

    See conjugate_expr() for why this cannot be as_real_imag() (which
    would also split the real symbols into real and imaginary parts).
    """
    conj = conjugate_expr(e)
    return (cancel((e + conj)/2), cancel((e - conj)/(2*I)))


def coupled_DE_system(f1, f2, g1, g2, DE):
    """
    Solve a Coupled Differential System: Dy1 + f1*y1 - f2*y2 == g1,
    Dy2 + f2*y1 + f1*y2 == g2.

    Explanation
    ===========

    Given a derivation D on k(t) with sqrt(-1) not in k(t) and f1,
    f2, g1, g2 in k(t), each given as a tuple (fa, fd) of Polys in
    DE.t, either raise NonElementaryIntegralException, in which case
    the system has no solution in k(t) x k(t), or return a solution
    (y1, y2), each again a tuple of Polys in DE.t.

    This solves the system through the equivalent Risch differential
    equation Dy + (f1 + f2*sqrt(-1))*y == g1 + g2*sqrt(-1) over
    k(sqrt(-1))(t), whose solutions are exactly y == y1 + y2*sqrt(-1)
    for solutions (y1, y2) of the system (Chapter 8 of Bronstein's
    book; the book gives no named pseudocode for this reduction).
    The recursive subproblems this generates are solved over
    extensions of k(sqrt(-1)) rather than through the real coupled
    cancellation algorithms of Sections 8.1-8.4, which the Risch
    differential equation code does not call yet.
    """
    f1a, f1d = frac_in(f1, DE.t)
    f2a, f2d = frac_in(f2, DE.t)
    g1a, g1d = frac_in(g1, DE.t)
    g2a, g2d = frac_in(g2, DE.t)
    fa, fd = frac_in(f1a.as_expr()/f1d.as_expr() +
        I*f2a.as_expr()/f2d.as_expr(), DE.t, cancel=True)
    ga, gd = frac_in(g1a.as_expr()/g1d.as_expr() +
        I*g2a.as_expr()/g2d.as_expr(), DE.t, cancel=True)
    ya, yd = rischDE(fa, fd, ga, gd, DE)
    y1, y2 = real_imag_expr(ya.as_expr()/yd.as_expr())
    return (frac_in(y1, DE.t, cancel=True), frac_in(y2, DE.t, cancel=True))


def param_coupled_DE_system(f1, f2, G, DE):
    """
    Solve a Parametric Coupled Differential System.

    Explanation
    ===========

    Given a derivation D on k(t) with sqrt(-1) not in k(t), f1, f2 in
    k(t), each given as a tuple (fa, fd) of Polys in DE.t, and G =
    [(g11, g21), ..., (g1m, g2m)] a list of pairs of such tuples,
    return H = [(u1, v1), ..., (ur, vr)], a list of pairs of tuples of
    Polys in DE.t, and a matrix A with m + 2*r' columns (r == 2*r')
    and constant entries, such that

        Du + f1*u - f2*v == Sum(ci*g1i, (i, 1, m))
        Dv + f2*u + f1*v == Sum(ci*g2i, (i, 1, m))

    has a solution (u, v) in k(t) x k(t) with c1, ..., cm in Const(k)
    if and only if (u, v) == Sum(dj*(uj, vj), (j, 1, r)) where d1,
    ..., dr are in Const(k) and (c1, ..., cm, d1, ..., dr) is a
    solution of Ax == 0.

    This solves the system through the equivalent parametric Risch
    differential equation Dy + (f1 + f2*sqrt(-1))*y ==
    Sum(ci*(g1i + g2i*sqrt(-1))) over k(sqrt(-1))(t) (see
    coupled_DE_system()), splitting param_rischDE()'s basis and
    constraint matrix into real and imaginary parts: each complex
    basis element y == y1 + y2*sqrt(-1) with complex coefficient
    d == d1 + d2*sqrt(-1) contributes the real basis pairs (y1, y2)
    (for d1) and (-y2, y1) (for d2), and each complex constraint row
    A1 + A2*sqrt(-1) splits into the two real rows
    (A1c, A1d, -A2d) and (A2c, A2d, A1d) over the columns
    (c, d1's, d2's), using that the ci are real.  There is no
    counterpart in Bronstein's book.
    """
    f1a, f1d = frac_in(f1, DE.t)
    f2a, f2d = frac_in(f2, DE.t)
    fa, fd = frac_in(f1a.as_expr()/f1d.as_expr() +
        I*f2a.as_expr()/f2d.as_expr(), DE.t, cancel=True)
    Gc = []
    for g1, g2 in G:
        g1a, g1d = frac_in(g1, DE.t)
        g2a, g2d = frac_in(g2, DE.t)
        Gc.append(frac_in(g1a.as_expr()/g1d.as_expr() +
            I*g2a.as_expr()/g2d.as_expr(), DE.t, cancel=True))
    h, A = param_rischDE(fa, fd, Gc, DE)

    m = len(G)
    rc = len(h)
    H = []
    for ya, yd in h:
        y1, y2 = real_imag_expr(ya.as_expr()/yd.as_expr())
        H.append((frac_in(y1, DE.t, cancel=True),
            frac_in(y2, DE.t, cancel=True)))
    for ya, yd in h:
        y1, y2 = real_imag_expr(ya.as_expr()/yd.as_expr())
        H.append((frac_in(-y2, DE.t, cancel=True),
            frac_in(y1, DE.t, cancel=True)))

    def entry(i, j):
        if i < A.rows:
            # Real part of row i: A1c*c + A1d*d1 - A2d*d2 == 0.
            if j < m + rc:
                return real_imag_expr(A[i, j].as_expr())[0]
            return -real_imag_expr(A[i, j - rc].as_expr())[1]
        # Imaginary part of row i: A2c*c + A2d*d1 + A1d*d2 == 0.
        i -= A.rows
        if j < m + rc:
            return real_imag_expr(A[i, j].as_expr())[1]
        return real_imag_expr(A[i, j - rc].as_expr())[0]

    return (H, Matrix(2*A.rows, m + 2*rc, entry, DE.t))


def coupled_DE_cancel_prim(b1, b2, c1, c2, DE, n):
    """
    Coupled Differential System - Cancellation: Primitive case.

    Explanation
    ===========

    Given a derivation D on k[t], n either an integer or +oo, ``b1``,
    ``b2`` in k with ``b1 != 0`` or ``b2 != 0``, and ``c1``, ``c2``
    in k[t], with Dt in k and sqrt(-1) not in k(t), either raise
    NonElementaryIntegralException, in which case the system

        Dq1 + b1*q1 - b2*q2 == c1
        Dq2 + b2*q1 + b1*q2 == c2

    has no solution with both degrees at most n in k[t], or return a
    solution (q1, q2) of this system with deg(q1) <= n and
    deg(q2) <= n.  ``b1`` and ``b2`` are Polys in DE.t (of degree 0);
    ``c1`` and ``c2`` are Polys in DE.t.

    This is ``CoupledDECancelPrim`` from Section 8.1 of Bronstein's
    book, specialized to a == -1.
    """
    with DecrementLevel(DE):
        ba, bd = frac_in(b1.as_expr() + I*b2.as_expr(), DE.t, cancel=True)
        A = is_log_deriv_k_t_radical_in_field(ba, bd, DE)

    if A is not None:
        m, z = A
        if m == 1:  # b1 + b2*sqrt(-1) == Dz/z
            # D(z*q) == z*(Dq + b*q) for q == q1 + q2*sqrt(-1), so q
            # solves the system iff p == z*q satisfies Dp == z*c.
            # With z == z1 + z2*sqrt(-1), the real and imaginary
            # parts of Dp == z*c are the two integration problems
            # D(p1) == z1*c1 - z2*c2 and D(p2) == z2*c1 + z1*c2 in
            # k[t], and q is recovered as p*conj(z)/(z1**2 + z2**2).
            z1, z2 = real_imag_expr(z)
            p = []
            for rhs in [z1*c1.as_expr() - z2*c2.as_expr(),
                    z2*c1.as_expr() + z1*c2.as_expr()]:
                pa, pd = frac_in(rhs, DE.t, cancel=True)
                B = is_deriv_in_field(pa, pd, DE)
                if B is None:
                    raise NonElementaryIntegralException("z*c is not the "
                        "derivative of an element of k(t) in "
                        "coupled_DE_cancel_prim().")
                va, vd = B
                # For a primitive t, an antiderivative in k(t) of an
                # element of k[t] is itself in k[t] (it can have no
                # poles), and any additive constants C1, C2 keep
                # q + (C1 + C2*sqrt(-1))/z in k[t] x k[t] and solve
                # the homogeneous system, so any choice of p will do.
                p.append(va.as_expr()/vd.as_expr())
            p1, p2 = p
            zz = z1**2 + z2**2
            q1 = cancel((z1*p1 + z2*p2)/zz).as_poly(DE.t)
            q2 = cancel((z1*p2 - z2*p1)/zz).as_poly(DE.t)
            if q1 is None or q2 is None:
                raise NonElementaryIntegralException("p/z is not in k[t] "
                    "in coupled_DE_cancel_prim().")
            if q1.degree(DE.t) > n or q2.degree(DE.t) > n:
                raise NonElementaryIntegralException("deg(p/z) > n in "
                    "coupled_DE_cancel_prim().")
            return (q1, q2)

    if c1.is_zero and c2.is_zero:
        return (c1, c2)  # return (0, 0)

    if n < max(c1.degree(DE.t), c2.degree(DE.t)):
        raise NonElementaryIntegralException("n < deg(c) in "
            "coupled_DE_cancel_prim().")

    q1 = Poly(0, DE.t)
    q2 = Poly(0, DE.t)
    while not (c1.is_zero and c2.is_zero):
        m = max(c1.degree(DE.t), c2.degree(DE.t))
        if n < m:
            raise NonElementaryIntegralException("n < deg(c) in "
                "coupled_DE_cancel_prim().")
        with DecrementLevel(DE):
            s1, s2 = coupled_DE_system(frac_in(b1.as_expr(), DE.t),
                frac_in(b2.as_expr(), DE.t), frac_in(c1.nth(m), DE.t),
                frac_in(c2.nth(m), DE.t), DE)
        s1tm = Poly(s1[0].as_expr()/s1[1].as_expr()*DE.t**m, DE.t,
            expand=False)
        s2tm = Poly(s2[0].as_expr()/s2[1].as_expr()*DE.t**m, DE.t,
            expand=False)
        q1 += s1tm
        q2 += s2tm
        n = m - 1
        c1 -= derivation(s1tm, DE) + b1*s1tm - b2*s2tm
        c2 -= derivation(s2tm, DE) + b2*s1tm + b1*s2tm

    return (q1, q2)


def coupled_DE_cancel_exp(b1, b2, c1, c2, DE, n):
    """
    Coupled Differential System - Cancellation: Hyperexponential case.

    Explanation
    ===========

    Given a derivation D on k[t], n either an integer or +oo, ``b1``,
    ``b2`` in k with ``b1 != 0`` or ``b2 != 0``, and ``c1``, ``c2``
    in k[t], with Dt/t in k and sqrt(-1) not in k(t), either raise
    NonElementaryIntegralException, in which case the system

        Dq1 + b1*q1 - b2*q2 == c1
        Dq2 + b2*q1 + b1*q2 == c2

    has no solution with both degrees at most n in k[t], or return a
    solution (q1, q2) of this system with deg(q1) <= n and
    deg(q2) <= n.  ``b1`` and ``b2`` are Polys in DE.t (of degree 0);
    ``c1`` and ``c2`` are Polys in DE.t.

    This is ``CoupledDECancelExp`` from Section 8.2 of Bronstein's
    book, specialized to a == -1.  The book's final degree condition
    reads deg(p2) <= n, but the quantity that must be bounded is
    deg(q2) (the two coincide only when m == 0 and z is constant); it
    is checked here alongside deg(q1) <= n.
    """
    eta = DE.d.quo(Poly(DE.t, DE.t)).as_expr()

    with DecrementLevel(DE):
        etaa, etad = frac_in(eta, DE.t)
        ba, bd = frac_in(b1.as_expr() + I*b2.as_expr(), DE.t, cancel=True)
        A = parametric_log_deriv(ba, bd, etaa, etad, DE)

    if A is not None:
        a, m, z = A
        if a == 1:
            # b1 + b2*sqrt(-1) == Dz/z + m*Dt/t, so
            # D(z*t**m*q) == z*t**m*(Dq + b*q) for
            # q == q1 + q2*sqrt(-1).  Hence q solves the system iff
            # p == z*t**m*q satisfies Dp == z*t**m*c.  With
            # z == z1 + z2*sqrt(-1), the real and imaginary parts of
            # Dp == z*t**m*c are the two integration problems
            # D(p1) == (z1*c1 - z2*c2)*t**m and
            # D(p2) == (z2*c1 + z1*c2)*t**m in k<t>, and q is
            # recovered as p*conj(z)*t**(-m)/(z1**2 + z2**2), which
            # must be in k[t] x k[t] with degrees at most n.
            z1, z2 = real_imag_expr(z)
            p = []
            for rhs in [(z1*c1.as_expr() - z2*c2.as_expr())*DE.t**m,
                    (z2*c1.as_expr() + z1*c2.as_expr())*DE.t**m]:
                pa, pd = frac_in(rhs, DE.t, cancel=True)
                B = is_deriv_in_field(pa, pd, DE)
                if B is None:
                    raise NonElementaryIntegralException("z*t**m*c is not "
                        "the derivative of an element of k(t) in "
                        "coupled_DE_cancel_exp().")
                va, vd = B
                pj = cancel(va.as_expr()/vd.as_expr())
                if m > 0:
                    # p is determined only up to an additive constant.
                    # For m > 0 the true p == z*t**m*q has no t-free
                    # term (all its monomials have degree >= m), while
                    # a constant term would make p*t**(-m)/z
                    # non-polynomial, so remove it.
                    pj -= pj.subs(DE.t, 0)
                p.append(pj)
            p1, p2 = p
            zz = z1**2 + z2**2
            q1 = cancel((z1*p1 + z2*p2)/(zz*DE.t**m)).as_poly(DE.t)
            q2 = cancel((z1*p2 - z2*p1)/(zz*DE.t**m)).as_poly(DE.t)
            if q1 is None or q2 is None:
                raise NonElementaryIntegralException("p/(z*t**m) is not in "
                    "k[t] in coupled_DE_cancel_exp().")
            if max(q1.degree(DE.t), q2.degree(DE.t)) > n:
                if m < 0 and max(q1.degree(DE.t), q2.degree(DE.t)) == -m:
                    # The homogeneous solutions are
                    # (C1 + C2*sqrt(-1))*t**(-m)/z for constants C1,
                    # C2, so the t**(-m) coefficients of (q1, q2) are
                    # adjustable by the constants of integration
                    # exactly when z*(q1 + q2*sqrt(-1))'s t**(-m)
                    # coefficient is constant.
                    cc = cancel(z*(q1.nth(-m) + I*q2.nth(-m)))
                    if not cc.has(*DE.T):
                        q1 = q1 - Poly(q1.nth(-m)*DE.t**(-m), DE.t)
                        q2 = q2 - Poly(q2.nth(-m)*DE.t**(-m), DE.t)
                if max(q1.degree(DE.t), q2.degree(DE.t)) > n:
                    raise NonElementaryIntegralException(
                        "deg(p/(z*t**m)) > n in coupled_DE_cancel_exp().")
            return (q1, q2)

    if c1.is_zero and c2.is_zero:
        return (c1, c2)  # return (0, 0)

    if n < max(c1.degree(DE.t), c2.degree(DE.t)):
        raise NonElementaryIntegralException("n < deg(c) in "
            "coupled_DE_cancel_exp().")

    q1 = Poly(0, DE.t)
    q2 = Poly(0, DE.t)
    while not (c1.is_zero and c2.is_zero):
        m = max(c1.degree(DE.t), c2.degree(DE.t))
        if n < m:
            raise NonElementaryIntegralException("n < deg(c) in "
                "coupled_DE_cancel_exp().")
        # The system for the t**m coefficients has b1 + m*Dt/t in
        # place of b1.
        with DecrementLevel(DE):
            b1a, b1d = frac_in(b1.as_expr(), DE.t)
            b1a = b1a*etad + etaa*b1d*Poly(m, DE.t)
            b1d = b1d*etad
            s1, s2 = coupled_DE_system((b1a, b1d),
                frac_in(b2.as_expr(), DE.t), frac_in(c1.nth(m), DE.t),
                frac_in(c2.nth(m), DE.t), DE)
        s1tm = Poly(s1[0].as_expr()/s1[1].as_expr()*DE.t**m, DE.t,
            expand=False)
        s2tm = Poly(s2[0].as_expr()/s2[1].as_expr()*DE.t**m, DE.t,
            expand=False)
        q1 += s1tm
        q2 += s2tm
        n = m - 1
        c1 -= derivation(s1tm, DE) + b1*s1tm - b2*s2tm
        c2 -= derivation(s2tm, DE) + b2*s1tm + b1*s2tm

    return (q1, q2)


def coupled_DE_cancel_tan(b0, b2, c1, c2, DE, n):
    """
    Coupled Differential System - Cancellation: Hypertangent case.

    Explanation
    ===========

    Given a derivation D on k[t], an integer n, ``b0``, ``b2`` in k
    with ``b0 != 0`` or ``b2 != 0``, and ``c1``, ``c2`` in k[t], with
    Dt/(t**2 + 1) == eta in k and sqrt(-1) not in k(t), either raise
    NonElementaryIntegralException, in which case the system

        Dq1 + (b0 - n*eta*t)*q1 - b2*q2 == c1
        Dq2 + b2*q1 + (b0 - n*eta*t)*q2 == c2

    has no solution with both degrees at most n in k[t], or return a
    solution (q1, q2) of this system with deg(q1) <= n and
    deg(q2) <= n.  ``b0`` and ``b2`` are Polys in DE.t (of degree 0);
    ``c1`` and ``c2`` are Polys in DE.t.

    Unlike the primitive and hyperexponential cases, ``n`` must be an
    integer: the recursion descends from n to 0 one step at a time,
    so it does not terminate for n == +oo.  Its callers get n from
    bound_degree(), which is always finite in the nonlinear case.

    This is ``CoupledDECancelTan`` from Section 8.4 of Bronstein's
    book.  The book's statement of the system prints b0 + n*eta*t in
    the bottom-right entry of the matrix, but the entry is
    b0 - n*eta*t (the system is the real/imaginary split of
    Dq + (b0 - n*eta*t + b2*sqrt(-1))*q == c1 + c2*sqrt(-1), whose
    matrix has equal diagonal entries, as in equation (8.4) and in
    the book's own worked Example 8.4.1).
    """
    if n == oo:
        raise ValueError("n must be a finite integer in "
            "coupled_DE_cancel_tan().")
    if n < 0:
        if c1.is_zero and c2.is_zero:
            return (Poly(0, DE.t), Poly(0, DE.t))
        raise NonElementaryIntegralException("n < 0 and c != 0 in "
            "coupled_DE_cancel_tan().")

    if n == 0:
        if c1.degree(DE.t) > 0 or c2.degree(DE.t) > 0:
            raise NonElementaryIntegralException("deg(c) > 0 == n in "
                "coupled_DE_cancel_tan().")
        with DecrementLevel(DE):
            q1, q2 = coupled_DE_system(frac_in(b0.as_expr(), DE.t),
                frac_in(b2.as_expr(), DE.t), frac_in(c1.nth(0), DE.t),
                frac_in(c2.nth(0), DE.t), DE)
            q1 = q1[0].as_expr()/q1[1].as_expr()
            q2 = q2[0].as_expr()/q2[1].as_expr()
        return (Poly(q1, DE.t), Poly(q2, DE.t))

    eta = DE.d.exquo(Poly(DE.t**2 + 1, DE.t)).as_expr()

    # The t**n coefficients of any solution satisfy the coupled
    # system over k obtained by projecting mod t - sqrt(-1) (i.e.
    # evaluating at t == sqrt(-1)):
    # z1 + z2*sqrt(-1) == c1(sqrt(-1)) + c2(sqrt(-1))*sqrt(-1).
    A1, B1, _ = real_imag(c1, Poly(1, DE.t), DE.t)
    A2, B2, _ = real_imag(c2, Poly(1, DE.t), DE.t)
    z1 = A1.as_expr() - B2.as_expr()
    z2 = B1.as_expr() + A2.as_expr()

    with DecrementLevel(DE):
        s1, s2 = coupled_DE_system(frac_in(b0.as_expr(), DE.t),
            frac_in(b2.as_expr() - n*eta, DE.t), frac_in(z1, DE.t),
            frac_in(z2, DE.t), DE)
        s1 = s1[0].as_expr()/s1[1].as_expr()
        s2 = s2[0].as_expr()/s2[1].as_expr()

    # With r == s1 + s2*sqrt(-1), h == (q - r)/(t - sqrt(-1)) solves
    # the same kind of system with b2 + eta in place of b2 and a
    # degree bound of n - 1, whose right hand side d1 + d2*sqrt(-1)
    # is the exact quotient (N1 + N2*sqrt(-1))/(t - sqrt(-1)),
    # computed via the conjugate: d1 == (N1*t - N2)/(t**2 + 1) and
    # d2 == (N2*t + N1)/(t**2 + 1).
    N1 = c1 - Poly(z1, DE.t) + Poly(n*eta*(s1*DE.t + s2), DE.t)
    N2 = c2 - Poly(z2, DE.t) + Poly(n*eta*(s2*DE.t - s1), DE.t)
    tp = Poly(DE.t, DE.t)
    p2 = Poly(DE.t**2 + 1, DE.t)
    d1 = (N1*tp - N2).exquo(p2)
    d2 = (N2*tp + N1).exquo(p2)

    h1, h2 = coupled_DE_cancel_tan(b0, b2 + Poly(eta, DE.t), d1, d2, DE,
        n - 1)

    # q == h*(t - sqrt(-1)) + r
    return (h1*tp + h2 + Poly(s1, DE.t), h2*tp - h1 + Poly(s2, DE.t))
