import os
import subprocess
import glob

here = os.path.dirname(__file__)
grammar_file = os.path.join(here, "LaTeX.g4")
dir_latex_antlr = os.path.join(here, "_antlr")


def check_antlr_version():
    print("Checking antlr4 version...")

    try:
        print(subprocess.check_output(["antlr4"])
              .decode('utf-8').split("\n")[0])
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("The antlr4 command line tool is not installed, "
              "or not on your PATH\n"
              "> Please install it via your preferred package manager")
        return False


def build_parser(output_dir=dir_latex_antlr):
    check_antlr_version()

    print("Updating ANTLR-generated code in", output_dir)

    header = (
        "# AUTO-GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND\n"
    )

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    with open(os.path.join(output_dir, "__init__.py"), "w+") as fp:
        fp.write(header)

    args = [
        "antlr4",
        grammar_file,
        "-o", output_dir,
        # for now, not generating these as latex2sympy did not use them
        "-no-visitor",
        "-no-listener",
    ]

    print("Running code generation", "\n\t$", " ".join(args))
    subprocess.check_output(args, cwd=output_dir)

    print("Applying headers and renaming")
    for path in glob.glob(os.path.join(output_dir, "LaTeX*.*")):
        offset = 0
        new_path = os.path.join(output_dir,
                                os.path.basename(path).lower())
        with open(new_path, "w+") as out_file:
            if path.endswith(".py"):
                out_file.write(header)
                offset = 2
            with open(path) as in_file:
                out_file.writelines(in_file.readlines()[offset:])
        os.unlink(path)
        print("...", new_path)

    return True


if __name__ == "__main__":
    build_parser()
