from .quaternion import Quaternion
from .abstract import (
    AlgebraicStructure,
    Magma,
    Semigroup,
    LeftQuasigroup, RightQuasigroup, Quasigroup,
    Monoid,
    Loop,
    Group, AbelianGroup,
    Ring, CommutativeRing,
    Field,
    Module,
    VectorSpace,
    Algebra,
    FunctionAdditionOperator, FunctionAddition,
    FunctionScalarMultiplicationOperator,
    FunctionMultiplication,
)

__all__ = [
    "Quaternion",
    "AlgebraicStructure",
    "Magma",
    "Semigroup",
    "LeftQuasigroup", "RightQuasigroup", "Quasigroup",
    "Monoid",
    "Loop",
    "Group", "AbelianGroup",
    "Ring", "CommutativeRing",
    "Field",
    "Module",
    "VectorSpace",
    "Algebra",
    "FunctionAdditionOperator", "FunctionAddition",
    "FunctionScalarMultiplicationOperator",
    "FunctionMultiplication",
]
