#! /bin/bash
# Executes all examples, that are working (mainly for testing purposes).
#
# Usage:
#
# When all examples run:
#   $ ./all > out
#   $
#
# When some examples fail:
#   $ ./all > out
#   Traceback (most recent call last):
#     File "./limits_examples.py", line 17, in ?
#   [...]
#   $
#
# Obviously, we want to achieve the first result.

# The commented out examples don't run

# Beginner Examples
./beginner/basic.py
./beginner/differentiation.py
./beginner/expansion.py
./beginner/functions.py
./beginner/limits_examples.py
#./beginner/plotting_nice_plot.py
./beginner/precision.py
./beginner/print_pretty.py
./beginner/series.py
./beginner/substitution.py

# Intermediate Examples
#./intermediate/differential_equations.py
#./intermediate/mplot2d.py
#./intermediate/mplot3d.py
#./intermediate/print_gtk.py
./intermediate/trees.py
./intermediate/vandermonde.py

# Advanced Examples
./advanced/fem_test.py
./advanced/gibbs_phenomenon.py
#./advanced/pidigits.py
#./advanced/plotting.py
#./advanced/qft.py
./advanced/relativity.py
#./advanced/tensors.py







