#! /bin/bash
# Executes all examples, that are working (mainly for testing purposes).
#
# Usage:
#
# When all examples run:
#   $ ./all > out
#   $
#
# When some examples fail:
#   $ ./all > out
#   Traceback (most recent call last):
#     File "./limits_examples.py", line 17, in ?
#   [...]
#   $
#
# Obviously, we want to achieve the first result.

# The commented out examples below don't run:
./basic.py
#./mplot3d.py
./relativity.py
./differential_equations.py
#./pidigits.py
./differentiation.py
#./plotting_nice_plot.py
./series.py
./expansion.py
#./plotting.py
./substitution.py
./precision.py
#./tensors.py
./fem_test.py
#./print_gtk.py
./t.py
./functions.py
./print_pretty.py
./trees.py
#./print_pygame.py
./vandermonde.py
./limits_examples.py
#./qft.py
#./mplot2d.py
