#!/usr/bin/env python

"""all.py

Runs all the examples for testing purposes and reports success and failure
to stderr.  An example is marked successful if the running thread does not
throw an exception, for threaded examples, such as plotting, one needs to
check the stderr messages as well.

   $ ./all.py [-hw] [--hide-output] [--hide-summary] [--simple-status]

Options:
    -h               print this help message and exit
    -w               Also run examples requiring windowed environment.
    --hide-output    Hide output generated by the examples.
    --hide-summary   Hides the summary at the end of running all examples.
    --simple-status  Shows simple status messages.  Will enable --hide-output.

Example Usage:
   When no examples fail:
     $ ./all.py > out
     SUCCESSFUL:
       - beginner.basic
       [...]
     NO FAILED EXAMPLES
     $

   When examples fail:
     $ ./all.py -w > out
     Traceback (most recent call last):
       File "./all.py", line 111, in run_examples
     [...]
     SUCCESSFUL:
       - beginner.basic
       [...]
     FAILED:
       - intermediate.mplot2D
       [...]
     $

   Obviously, we want to achieve the first result.
"""

import imp
import os
import sys
import traceback
import getopt

TERMINAL_EXAMPLES = [
    "beginner.basic",
    "beginner.differentiation",
    "beginner.expansion",
    "beginner.functions",
    "beginner.limits_examples",
    "beginner.precision",
    "beginner.print_pretty",
    "beginner.series",
    "beginner.substitution",
    "intermediate.coupled_cluster",
    "intermediate.differential_equations",
    "intermediate.infinite_1d_box",
    "intermediate.partial_differential_eqs",
    "intermediate.trees",
    "intermediate.vandermonde",
    "advanced.curvilinear_coordinates",
    "advanced.fem",
    "advanced.gibbs_phenomenon",
    "advanced.grover_example",
    "advanced.pidigits",
    "advanced.qft",
    "advanced.relativity",
    ]

WINDOWED_EXAMPLES = [
    "beginner.plotting_nice_plot",
    "intermediate.print_gtk",
    "intermediate.mplot2d",
    "intermediate.mplot3d",
    "advanced.autowrap_integrators",
    "advanced.autowrap_ufuncify",
    "advanced.plotting",
    ]

EXAMPLE_DIR = os.path.dirname(__file__)

def __import__(name, globals=None, locals=None, fromlist=None):
    """An alternative to the import function so that we can import
    modules defined as strings.

    This code was taken from: http://docs.python.org/lib/examples-imp.html
    """
    # Fast path: see if the module has already been imported.
    try:
        return sys.modules[name]
    except KeyError:
        pass

    # If any of the following calls raises an exception,
    # there's a problem we can't handle -- let the caller handle it.
    module_name = name.split('.')[-1]
    module_path = os.path.join(EXAMPLE_DIR, *name.split('.')[:-1])

    fp, pathname, description = imp.find_module(module_name, [module_path])

    this_file = os.path.abspath(__file__)
    sympy_dir = os.path.join(os.path.dirname(this_file), "..")
    sympy_dir = os.path.normpath(sympy_dir)
    sys.path.insert(0, sympy_dir)

    try:
        return imp.load_module(module_name, fp, pathname, description)
    finally:
        # Since we may exit via an exception, close fp explicitly.
        if fp:
            fp.close()


def load_example_module(example):
    """Loads modules based upon the given package name"""
    mod = __import__(example)
    return mod


def run_examples(windowed=False, hide_output=False, hide_summary=False,
                 simple_status=False):
    """Run example in list of modules"""
    successes = []
    failures = []
    examples = TERMINAL_EXAMPLES
    if windowed:
        examples += WINDOWED_EXAMPLES

    for example in examples:
        if run_example(example, hide_output, simple_status):
            successes.append(example)
        else:
            failures.append(example)

    if not hide_summary:
        show_summary(successes, failures)

    return 1 if failures else 0


class DummyFile(object):
    def write(self, x): pass


def run_example(example, hide_output=False, simple_status=False):
    """Run a specific example.
    
    Returns a boolean value indicating whether the example was successful.
    """
    if simple_status:
        print example, "...",
    else:
        print "=" * 79
        print "Running: ", example

    try:
        mod = load_example_module(example)

        if hide_output:
            # suppress output
            save_stdout = sys.stdout
            sys.stdout = DummyFile()
            mod.main()
            sys.stdout = save_stdout
        else:
            mod.main()

        if simple_status:
            print "success"
        return True

    except ImportError:
        if simple_status:
            print "fail"
        traceback.print_exc()
        return False


def show_summary(successes, failures):
    """Shows a summary detailing which examples were successful and which failed."""
    if successes:
        print >> sys.stderr, "SUCCESSFUL: "
        for example in successes:
            print >> sys.stderr, "  -", example
    else:
        print >> sys.stderr, "NO SUCCESSFUL EXAMPLES"

    if failures:
        print >> sys.stderr, "FAILED: "
        for example in failures:
            print >> sys.stderr, "  -", example
    else:
        print >> sys.stderr, "NO FAILED EXAMPLES"


def main(*args, **kws):
    """Main script runner"""
    use_windowed = False
    hide_output = False
    hide_summary = False
    simple_status = False

    try:
        opts, remainder = getopt.getopt(args, "hw", ["hide-output", "hide-summary", "simple-status"])
        for opt_key, opt_val in opts:
            if opt_key == '-w':
                use_windowed = True
            elif opt_key == "-h":
                print __doc__
                sys.exit(0)
            elif opt_key == "--hide-output":
                hide_output = True
            elif opt_key == "--hide-summary":
                hide_summary = True
            elif opt_key == "--simple-status":
                simple_status = True
                hide_output = True
            else:
                raise getopt.GetoptError, "option %s not processed" % opt_key
    except getopt.GetoptError, message:
        print >> sys.stderr, message
        print >> sys.stderr, "Use -h option for usage.\n"
        sys.exit(1)

    return run_examples(use_windowed, hide_output, hide_summary, simple_status)


if __name__ == "__main__":
    sys.exit(main(*sys.argv[1:]))
