from sympy.core import Basic
from sympy.core.backend import zeros, Matrix

class Standard_Cartan(Basic):
    """
    Semi-Concrete base class for Cartan types such as A4, etc
    """

    def __new__(cls, series, n):
        obj = Basic.__new__(cls, series, n)
        obj.n = n
        obj.series = series
        return obj

    def rank(self):
        """
        Returns the rank of the Lie algebra
        """
        return self.n

    def series(self):
        """
        Returns the type of the Lie algebra
        """
        return self.series

    def cartan_matrix(self):
        """
        Returns the Cartan Matrix for the algebra. For a
        given simple Lie algabra the elements `a_ij` can be
        generated by

        a_ji = 2 <\u03B1_i, \u03B1_j> / <\u03B1_j, \u03B1_j>

        where a_i is the i'th simple root and <,> is the scalar product.
        """
        r = self.rank()
        cartan_matrix = zeros(r,r)
        for i, sr_i in enumerate(self.simple_roots()):
            for j, sr_j in enumerate(self.simple_roots()):
                cartan_matrix[j,i] = 2 * sr_i.dot(sr_j) / sr_i.dot(sr_i)
        return cartan_matrix

    def cocartan_matrix(self):
        """
        Returns the Cocartan matrix. The Cocartan matrix
        row elements, c_i, are built from covectors of simple roots, \u03B1_i.

        c_i = 2 \u03B1_i / <\u03B1_i, \u03B1_i>

        This relationship is helpful in defining the orthogonal base where
        multiplying by some weight, w_j, yields the unit matrix.

        <c_i, w_j> = KroneckerDelta[i,j].
        """
        return Matrix([
                2 * x / x.dot(x) for x in self.simple_roots()])

    def omega_matrix(self):
        """
        Returns the omega matrix, which rows are built from
        the fundamental weights of the algebra in the orthogonal
        basis.
        """
        return self.cocartan_matrix().pinv().T

    def simple_root(self, i):
        """
        Returns the i'th simple root in the orthogonal basis.
        """
        raise NotImplementedError("Do not call this method directly from the base class.")

    def simple_roots(self):
        """
        Returns the simple roots of the algebra.
        """
        return [Matrix(self.simple_root(i+1)).T for i in range(self.n)]

    def fundamental_weight(self, i):
        """
        Returns the i'th fundamental weight of the algebra in the
        orthogonal basis.

        Explanation
        ===========
        The weights of an algebra, \u03BB, can be
        written as a linear combination of the simple roots, \u03B1_i.
        The following theorem,

        a_i = 2<\u03BB, \u03B1_i> / <\u03B1_i, \u03B1_i>

        where a_i are the Dynkin labels.  The fundamental weights
        of the algebra are the weights, \u03BB, with the smallest a_i >=0.
        Note that if \u03BB_i==\u03B1_i, then the Dynkin labels become
        the elements of the Cartan matrix.

        Sources
        =======
        - https://en.wikipedia.org/wiki/Weight_(representation_theory)
        - http://www.math.columbia.edu/~woit/notes11.pdf
        """
        return self.omega_matrix().row(i)

    def fundamental_weights(self):
        """
        Returns a list of the fundamental weights in the orthogonal basis
        """
        return [self.fundamental_weight(i) for i in range(self.omega_matrix().rows)]
