
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys



def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"Y\u038f\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u"\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4")
        buf.write(u"$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\t")
        buf.write(u"J\4K\tK\4L\tL\4M\tM\4N\tN\4O\tO\4P\tP\4Q\tQ\4R\tR\4S")
        buf.write(u"\tS\4T\tT\4U\tU\4V\tV\4W\tW\4X\tX\4Y\tY\4Z\tZ\3\2\3\2")
        buf.write(u"\3\3\6\3\u00b9\n\3\r\3\16\3\u00ba\3\3\3\3\3\4\3\4\3\4")
        buf.write(u"\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5\4\u00cb\n\4\3")
        buf.write(u"\4\3\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\5")
        buf.write(u"\5\u00da\n\5\3\5\3\5\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6")
        buf.write(u"\3\6\3\6\3\6\3\6\3\6\5\6\u00eb\n\6\3\6\3\6\3\7\3\7\3")
        buf.write(u"\7\3\7\3\7\3\7\3\7\3\7\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3")
        buf.write(u"\b\3\b\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3")
        buf.write(u"\t\3\t\3\t\3\t\5\t\u010f\n\t\3\t\3\t\3\n\3\n\3\n\3\n")
        buf.write(u"\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\13\3\13")
        buf.write(u"\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3")
        buf.write(u"\13\3\13\3\13\3\13\3\13\3\f\3\f\3\f\3\f\3\f\3\f\3\f\3")
        buf.write(u"\f\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\r\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3")
        buf.write(u"\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16\3\16")
        buf.write(u"\3\16\3\16\3\16\3\16\3\16\3\16\5\16\u0177\n\16\3\16\3")
        buf.write(u"\16\3\17\3\17\3\20\3\20\3\21\3\21\3\22\3\22\3\23\3\23")
        buf.write(u"\3\24\3\24\3\25\3\25\3\26\3\26\3\27\3\27\3\27\3\30\3")
        buf.write(u"\30\3\30\3\31\3\31\3\32\3\32\3\33\3\33\3\34\3\34\3\34")
        buf.write(u"\3\34\3\34\3\34\3\34\3\34\3\35\3\35\3\35\3\35\3\35\3")
        buf.write(u"\35\3\35\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\36\3\37")
        buf.write(u"\3\37\3\37\3\37\3\37\3\37\3\37\3\37\3 \3 \3 \3 \3 \3")
        buf.write(u"!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!")
        buf.write(u"\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3")
        buf.write(u"!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!\3!")
        buf.write(u"\3!\3!\5!\u01f2\n!\3\"\3\"\3\"\3\"\3\"\3#\3#\3#\3#\3")
        buf.write(u"#\3#\3#\3#\3#\3#\5#\u0203\n#\3$\3$\3$\3$\3$\3$\3$\3$")
        buf.write(u"\5$\u020d\n$\3%\3%\3%\3%\3%\3&\3&\3&\3&\3&\3\'\3\'\3")
        buf.write(u"\'\3\'\3(\3(\3(\3(\3(\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3")
        buf.write(u"+\3+\3+\3+\3+\3,\3,\3,\3,\3,\3-\3-\3-\3-\3-\3.\3.\3.")
        buf.write(u"\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/\3/\3/\3\60\3\60\3\60")
        buf.write(u"\3\60\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3\61\3\61\3")
        buf.write(u"\61\3\61\3\61\3\62\3\62\3\62\3\62\3\62\3\62\3\62\3\62")
        buf.write(u"\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\63\3\64\3\64\3")
        buf.write(u"\64\3\64\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\66")
        buf.write(u"\3\66\3\66\3\66\3\66\3\66\3\67\3\67\3\67\3\67\3\67\3")
        buf.write(u"\67\3\67\3\67\38\38\38\38\38\38\38\38\39\39\39\39\39")
        buf.write(u"\39\39\39\3:\3:\3:\3:\3:\3:\3:\3:\3;\3;\3;\3;\3;\3;\3")
        buf.write(u";\3;\3<\3<\3<\3<\3<\3<\3<\3=\3=\3=\3=\3=\3=\3=\3>\3>")
        buf.write(u"\3>\3>\3>\3>\3?\3?\3?\3?\3?\3?\3?\3@\3@\3@\3@\3@\3@\3")
        buf.write(u"A\3A\3A\3A\3A\3B\3B\3B\3B\3B\3B\3C\3C\3C\3C\3C\3C\3C")
        buf.write(u"\3D\3D\3D\3D\3D\3D\3D\3D\3E\3E\3E\3E\3E\3E\3E\3E\3F\3")
        buf.write(u"F\3F\3F\3F\3F\3F\3F\3G\3G\3H\3H\3I\3I\3J\3J\3K\3K\7K")
        buf.write(u"\u02fa\nK\fK\16K\u02fd\13K\3K\3K\3K\6K\u0302\nK\rK\16")
        buf.write(u"K\u0303\5K\u0306\nK\3L\3L\3M\3M\3N\6N\u030d\nN\rN\16")
        buf.write(u"N\u030e\3N\3N\3N\3N\3N\7N\u0316\nN\fN\16N\u0319\13N\3")
        buf.write(u"N\7N\u031c\nN\fN\16N\u031f\13N\3N\3N\3N\3N\3N\7N\u0326")
        buf.write(u"\nN\fN\16N\u0329\13N\3N\3N\6N\u032d\nN\rN\16N\u032e\5")
        buf.write(u"N\u0331\nN\3O\3O\7O\u0335\nO\fO\16O\u0338\13O\5O\u033a")
        buf.write(u"\nO\3O\3O\3O\7O\u033f\nO\fO\16O\u0342\13O\3O\5O\u0345")
        buf.write(u"\nO\5O\u0347\nO\3P\3P\3P\3P\3P\3Q\3Q\3R\3R\3R\3R\3R\3")
        buf.write(u"R\3R\3R\3R\5R\u0359\nR\3S\3S\3S\3S\3S\3S\3T\3T\3T\3T")
        buf.write(u"\3T\3T\3T\3T\3T\3T\3U\3U\3V\3V\3V\3V\3V\3V\3V\3V\3V\5")
        buf.write(u"V\u0376\nV\3W\3W\3W\3W\3W\3W\3X\3X\3X\3X\3X\3X\3X\3X")
        buf.write(u"\3X\3X\3Y\3Y\3Z\3Z\6Z\u038c\nZ\rZ\16Z\u038d\5\u02fb\u0336")
        buf.write(u"\u0340\2[\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n\23\13\25")
        buf.write(u"\f\27\r\31\16\33\17\35\20\37\21!\22#\23%\24\'\25)\26")
        buf.write(u"+\27-\30/\31\61\32\63\33\65\34\67\359\36;\37= ?!A\"C")
        buf.write(u"#E$G%I&K\'M(O)Q*S+U,W-Y.[/]\60_\61a\62c\63e\64g\65i\66")
        buf.write(u"k\67m8o9q:s;u<w=y>{?}@\177A\u0081B\u0083C\u0085D\u0087")
        buf.write(u"E\u0089F\u008bG\u008dH\u008fI\u0091J\u0093\2\u0095K\u0097")
        buf.write(u"L\u0099\2\u009bM\u009dN\u009fO\u00a1P\u00a3Q\u00a5R\u00a7")
        buf.write(u"S\u00a9T\u00abU\u00adV\u00afW\u00b1X\u00b3Y\3\2\5\5\2")
        buf.write(u"\13\f\17\17\"\"\4\2C\\c|\3\2\62;\2\u03b8\2\3\3\2\2\2")
        buf.write(u"\2\5\3\2\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r")
        buf.write(u"\3\2\2\2\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25")
        buf.write(u"\3\2\2\2\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35")
        buf.write(u"\3\2\2\2\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2")
        buf.write(u"\2\2\'\3\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2\2\2\2/\3")
        buf.write(u"\2\2\2\2\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2\2\67\3")
        buf.write(u"\2\2\2\29\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2\2\2\2")
        buf.write(u"A\3\2\2\2\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2I\3\2\2\2")
        buf.write(u"\2K\3\2\2\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2\2S\3\2\2")
        buf.write(u"\2\2U\3\2\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2\2]\3\2")
        buf.write(u"\2\2\2_\3\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2\2\2\2g\3")
        buf.write(u"\2\2\2\2i\3\2\2\2\2k\3\2\2\2\2m\3\2\2\2\2o\3\2\2\2\2")
        buf.write(u"q\3\2\2\2\2s\3\2\2\2\2u\3\2\2\2\2w\3\2\2\2\2y\3\2\2\2")
        buf.write(u"\2{\3\2\2\2\2}\3\2\2\2\2\177\3\2\2\2\2\u0081\3\2\2\2")
        buf.write(u"\2\u0083\3\2\2\2\2\u0085\3\2\2\2\2\u0087\3\2\2\2\2\u0089")
        buf.write(u"\3\2\2\2\2\u008b\3\2\2\2\2\u008d\3\2\2\2\2\u008f\3\2")
        buf.write(u"\2\2\2\u0091\3\2\2\2\2\u0095\3\2\2\2\2\u0097\3\2\2\2")
        buf.write(u"\2\u009b\3\2\2\2\2\u009d\3\2\2\2\2\u009f\3\2\2\2\2\u00a1")
        buf.write(u"\3\2\2\2\2\u00a3\3\2\2\2\2\u00a5\3\2\2\2\2\u00a7\3\2")
        buf.write(u"\2\2\2\u00a9\3\2\2\2\2\u00ab\3\2\2\2\2\u00ad\3\2\2\2")
        buf.write(u"\2\u00af\3\2\2\2\2\u00b1\3\2\2\2\2\u00b3\3\2\2\2\3\u00b5")
        buf.write(u"\3\2\2\2\5\u00b8\3\2\2\2\7\u00ca\3\2\2\2\t\u00d9\3\2")
        buf.write(u"\2\2\13\u00ea\3\2\2\2\r\u00ee\3\2\2\2\17\u00f6\3\2\2")
        buf.write(u"\2\21\u010e\3\2\2\2\23\u0112\3\2\2\2\25\u0121\3\2\2\2")
        buf.write(u"\27\u0132\3\2\2\2\31\u013a\3\2\2\2\33\u0176\3\2\2\2\35")
        buf.write(u"\u017a\3\2\2\2\37\u017c\3\2\2\2!\u017e\3\2\2\2#\u0180")
        buf.write(u"\3\2\2\2%\u0182\3\2\2\2\'\u0184\3\2\2\2)\u0186\3\2\2")
        buf.write(u"\2+\u0188\3\2\2\2-\u018a\3\2\2\2/\u018d\3\2\2\2\61\u0190")
        buf.write(u"\3\2\2\2\63\u0192\3\2\2\2\65\u0194\3\2\2\2\67\u0196\3")
        buf.write(u"\2\2\29\u019e\3\2\2\2;\u01a5\3\2\2\2=\u01ad\3\2\2\2?")
        buf.write(u"\u01b5\3\2\2\2A\u01f1\3\2\2\2C\u01f3\3\2\2\2E\u0202\3")
        buf.write(u"\2\2\2G\u020c\3\2\2\2I\u020e\3\2\2\2K\u0213\3\2\2\2M")
        buf.write(u"\u0218\3\2\2\2O\u021c\3\2\2\2Q\u0221\3\2\2\2S\u0226\3")
        buf.write(u"\2\2\2U\u022b\3\2\2\2W\u0230\3\2\2\2Y\u0235\3\2\2\2[")
        buf.write(u"\u023a\3\2\2\2]\u0242\3\2\2\2_\u024a\3\2\2\2a\u0252\3")
        buf.write(u"\2\2\2c\u025a\3\2\2\2e\u0262\3\2\2\2g\u026a\3\2\2\2i")
        buf.write(u"\u0270\3\2\2\2k\u0276\3\2\2\2m\u027c\3\2\2\2o\u0284\3")
        buf.write(u"\2\2\2q\u028c\3\2\2\2s\u0294\3\2\2\2u\u029c\3\2\2\2w")
        buf.write(u"\u02a4\3\2\2\2y\u02ab\3\2\2\2{\u02b2\3\2\2\2}\u02b8\3")
        buf.write(u"\2\2\2\177\u02bf\3\2\2\2\u0081\u02c5\3\2\2\2\u0083\u02ca")
        buf.write(u"\3\2\2\2\u0085\u02d0\3\2\2\2\u0087\u02d7\3\2\2\2\u0089")
        buf.write(u"\u02df\3\2\2\2\u008b\u02e7\3\2\2\2\u008d\u02ef\3\2\2")
        buf.write(u"\2\u008f\u02f1\3\2\2\2\u0091\u02f3\3\2\2\2\u0093\u02f5")
        buf.write(u"\3\2\2\2\u0095\u02f7\3\2\2\2\u0097\u0307\3\2\2\2\u0099")
        buf.write(u"\u0309\3\2\2\2\u009b\u0330\3\2\2\2\u009d\u0346\3\2\2")
        buf.write(u"\2\u009f\u0348\3\2\2\2\u00a1\u034d\3\2\2\2\u00a3\u0358")
        buf.write(u"\3\2\2\2\u00a5\u035a\3\2\2\2\u00a7\u0360\3\2\2\2\u00a9")
        buf.write(u"\u036a\3\2\2\2\u00ab\u0375\3\2\2\2\u00ad\u0377\3\2\2")
        buf.write(u"\2\u00af\u037d\3\2\2\2\u00b1\u0387\3\2\2\2\u00b3\u0389")
        buf.write(u"\3\2\2\2\u00b5\u00b6\7.\2\2\u00b6\4\3\2\2\2\u00b7\u00b9")
        buf.write(u"\t\2\2\2\u00b8\u00b7\3\2\2\2\u00b9\u00ba\3\2\2\2\u00ba")
        buf.write(u"\u00b8\3\2\2\2\u00ba\u00bb\3\2\2\2\u00bb\u00bc\3\2\2")
        buf.write(u"\2\u00bc\u00bd\b\3\2\2\u00bd\6\3\2\2\2\u00be\u00bf\7")
        buf.write(u"^\2\2\u00bf\u00cb\7.\2\2\u00c0\u00c1\7^\2\2\u00c1\u00c2")
        buf.write(u"\7v\2\2\u00c2\u00c3\7j\2\2\u00c3\u00c4\7k\2\2\u00c4\u00c5")
        buf.write(u"\7p\2\2\u00c5\u00c6\7u\2\2\u00c6\u00c7\7r\2\2\u00c7\u00c8")
        buf.write(u"\7c\2\2\u00c8\u00c9\7e\2\2\u00c9\u00cb\7g\2\2\u00ca\u00be")
        buf.write(u"\3\2\2\2\u00ca\u00c0\3\2\2\2\u00cb\u00cc\3\2\2\2\u00cc")
        buf.write(u"\u00cd\b\4\2\2\u00cd\b\3\2\2\2\u00ce\u00cf\7^\2\2\u00cf")
        buf.write(u"\u00da\7<\2\2\u00d0\u00d1\7^\2\2\u00d1\u00d2\7o\2\2\u00d2")
        buf.write(u"\u00d3\7g\2\2\u00d3\u00d4\7f\2\2\u00d4\u00d5\7u\2\2\u00d5")
        buf.write(u"\u00d6\7r\2\2\u00d6\u00d7\7c\2\2\u00d7\u00d8\7e\2\2\u00d8")
        buf.write(u"\u00da\7g\2\2\u00d9\u00ce\3\2\2\2\u00d9\u00d0\3\2\2\2")
        buf.write(u"\u00da\u00db\3\2\2\2\u00db\u00dc\b\5\2\2\u00dc\n\3\2")
        buf.write(u"\2\2\u00dd\u00de\7^\2\2\u00de\u00eb\7=\2\2\u00df\u00e0")
        buf.write(u"\7^\2\2\u00e0\u00e1\7v\2\2\u00e1\u00e2\7j\2\2\u00e2\u00e3")
        buf.write(u"\7k\2\2\u00e3\u00e4\7e\2\2\u00e4\u00e5\7m\2\2\u00e5\u00e6")
        buf.write(u"\7u\2\2\u00e6\u00e7\7r\2\2\u00e7\u00e8\7c\2\2\u00e8\u00e9")
        buf.write(u"\7e\2\2\u00e9\u00eb\7g\2\2\u00ea\u00dd\3\2\2\2\u00ea")
        buf.write(u"\u00df\3\2\2\2\u00eb\u00ec\3\2\2\2\u00ec\u00ed\b\6\2")
        buf.write(u"\2\u00ed\f\3\2\2\2\u00ee\u00ef\7^\2\2\u00ef\u00f0\7s")
        buf.write(u"\2\2\u00f0\u00f1\7w\2\2\u00f1\u00f2\7c\2\2\u00f2\u00f3")
        buf.write(u"\7f\2\2\u00f3\u00f4\3\2\2\2\u00f4\u00f5\b\7\2\2\u00f5")
        buf.write(u"\16\3\2\2\2\u00f6\u00f7\7^\2\2\u00f7\u00f8\7s\2\2\u00f8")
        buf.write(u"\u00f9\7s\2\2\u00f9\u00fa\7w\2\2\u00fa\u00fb\7c\2\2\u00fb")
        buf.write(u"\u00fc\7f\2\2\u00fc\u00fd\3\2\2\2\u00fd\u00fe\b\b\2\2")
        buf.write(u"\u00fe\20\3\2\2\2\u00ff\u0100\7^\2\2\u0100\u010f\7#\2")
        buf.write(u"\2\u0101\u0102\7^\2\2\u0102\u0103\7p\2\2\u0103\u0104")
        buf.write(u"\7g\2\2\u0104\u0105\7i\2\2\u0105\u0106\7v\2\2\u0106\u0107")
        buf.write(u"\7j\2\2\u0107\u0108\7k\2\2\u0108\u0109\7p\2\2\u0109\u010a")
        buf.write(u"\7u\2\2\u010a\u010b\7r\2\2\u010b\u010c\7c\2\2\u010c\u010d")
        buf.write(u"\7e\2\2\u010d\u010f\7g\2\2\u010e\u00ff\3\2\2\2\u010e")
        buf.write(u"\u0101\3\2\2\2\u010f\u0110\3\2\2\2\u0110\u0111\b\t\2")
        buf.write(u"\2\u0111\22\3\2\2\2\u0112\u0113\7^\2\2\u0113\u0114\7")
        buf.write(u"p\2\2\u0114\u0115\7g\2\2\u0115\u0116\7i\2\2\u0116\u0117")
        buf.write(u"\7o\2\2\u0117\u0118\7g\2\2\u0118\u0119\7f\2\2\u0119\u011a")
        buf.write(u"\7u\2\2\u011a\u011b\7r\2\2\u011b\u011c\7c\2\2\u011c\u011d")
        buf.write(u"\7e\2\2\u011d\u011e\7g\2\2\u011e\u011f\3\2\2\2\u011f")
        buf.write(u"\u0120\b\n\2\2\u0120\24\3\2\2\2\u0121\u0122\7^\2\2\u0122")
        buf.write(u"\u0123\7p\2\2\u0123\u0124\7g\2\2\u0124\u0125\7i\2\2\u0125")
        buf.write(u"\u0126\7v\2\2\u0126\u0127\7j\2\2\u0127\u0128\7k\2\2\u0128")
        buf.write(u"\u0129\7e\2\2\u0129\u012a\7m\2\2\u012a\u012b\7u\2\2\u012b")
        buf.write(u"\u012c\7r\2\2\u012c\u012d\7c\2\2\u012d\u012e\7e\2\2\u012e")
        buf.write(u"\u012f\7g\2\2\u012f\u0130\3\2\2\2\u0130\u0131\b\13\2")
        buf.write(u"\2\u0131\26\3\2\2\2\u0132\u0133\7^\2\2\u0133\u0134\7")
        buf.write(u"n\2\2\u0134\u0135\7g\2\2\u0135\u0136\7h\2\2\u0136\u0137")
        buf.write(u"\7v\2\2\u0137\u0138\3\2\2\2\u0138\u0139\b\f\2\2\u0139")
        buf.write(u"\30\3\2\2\2\u013a\u013b\7^\2\2\u013b\u013c\7t\2\2\u013c")
        buf.write(u"\u013d\7k\2\2\u013d\u013e\7i\2\2\u013e\u013f\7j\2\2\u013f")
        buf.write(u"\u0140\7v\2\2\u0140\u0141\3\2\2\2\u0141\u0142\b\r\2\2")
        buf.write(u"\u0142\32\3\2\2\2\u0143\u0144\7^\2\2\u0144\u0145\7x\2")
        buf.write(u"\2\u0145\u0146\7t\2\2\u0146\u0147\7w\2\2\u0147\u0148")
        buf.write(u"\7n\2\2\u0148\u0177\7g\2\2\u0149\u014a\7^\2\2\u014a\u014b")
        buf.write(u"\7x\2\2\u014b\u014c\7e\2\2\u014c\u014d\7g\2\2\u014d\u014e")
        buf.write(u"\7p\2\2\u014e\u014f\7v\2\2\u014f\u0150\7g\2\2\u0150\u0177")
        buf.write(u"\7t\2\2\u0151\u0152\7^\2\2\u0152\u0153\7x\2\2\u0153\u0154")
        buf.write(u"\7d\2\2\u0154\u0155\7q\2\2\u0155\u0177\7z\2\2\u0156\u0157")
        buf.write(u"\7^\2\2\u0157\u0158\7x\2\2\u0158\u0159\7u\2\2\u0159\u015a")
        buf.write(u"\7m\2\2\u015a\u015b\7k\2\2\u015b\u0177\7r\2\2\u015c\u015d")
        buf.write(u"\7^\2\2\u015d\u015e\7x\2\2\u015e\u015f\7u\2\2\u015f\u0160")
        buf.write(u"\7r\2\2\u0160\u0161\7c\2\2\u0161\u0162\7e\2\2\u0162\u0177")
        buf.write(u"\7g\2\2\u0163\u0164\7^\2\2\u0164\u0165\7j\2\2\u0165\u0166")
        buf.write(u"\7h\2\2\u0166\u0167\7k\2\2\u0167\u0177\7n\2\2\u0168\u0169")
        buf.write(u"\7^\2\2\u0169\u0177\7,\2\2\u016a\u016b\7^\2\2\u016b\u0177")
        buf.write(u"\7/\2\2\u016c\u016d\7^\2\2\u016d\u0177\7\60\2\2\u016e")
        buf.write(u"\u016f\7^\2\2\u016f\u0177\7\61\2\2\u0170\u0171\7^\2\2")
        buf.write(u"\u0171\u0177\7$\2\2\u0172\u0173\7^\2\2\u0173\u0177\7")
        buf.write(u"*\2\2\u0174\u0175\7^\2\2\u0175\u0177\7?\2\2\u0176\u0143")
        buf.write(u"\3\2\2\2\u0176\u0149\3\2\2\2\u0176\u0151\3\2\2\2\u0176")
        buf.write(u"\u0156\3\2\2\2\u0176\u015c\3\2\2\2\u0176\u0163\3\2\2")
        buf.write(u"\2\u0176\u0168\3\2\2\2\u0176\u016a\3\2\2\2\u0176\u016c")
        buf.write(u"\3\2\2\2\u0176\u016e\3\2\2\2\u0176\u0170\3\2\2\2\u0176")
        buf.write(u"\u0172\3\2\2\2\u0176\u0174\3\2\2\2\u0177\u0178\3\2\2")
        buf.write(u"\2\u0178\u0179\b\16\2\2\u0179\34\3\2\2\2\u017a\u017b")
        buf.write(u"\7-\2\2\u017b\36\3\2\2\2\u017c\u017d\7/\2\2\u017d \3")
        buf.write(u"\2\2\2\u017e\u017f\7,\2\2\u017f\"\3\2\2\2\u0180\u0181")
        buf.write(u"\7\61\2\2\u0181$\3\2\2\2\u0182\u0183\7*\2\2\u0183&\3")
        buf.write(u"\2\2\2\u0184\u0185\7+\2\2\u0185(\3\2\2\2\u0186\u0187")
        buf.write(u"\7}\2\2\u0187*\3\2\2\2\u0188\u0189\7\177\2\2\u0189,\3")
        buf.write(u"\2\2\2\u018a\u018b\7^\2\2\u018b\u018c\7}\2\2\u018c.\3")
        buf.write(u"\2\2\2\u018d\u018e\7^\2\2\u018e\u018f\7\177\2\2\u018f")
        buf.write(u"\60\3\2\2\2\u0190\u0191\7]\2\2\u0191\62\3\2\2\2\u0192")
        buf.write(u"\u0193\7_\2\2\u0193\64\3\2\2\2\u0194\u0195\7~\2\2\u0195")
        buf.write(u"\66\3\2\2\2\u0196\u0197\7^\2\2\u0197\u0198\7t\2\2\u0198")
        buf.write(u"\u0199\7k\2\2\u0199\u019a\7i\2\2\u019a\u019b\7j\2\2\u019b")
        buf.write(u"\u019c\7v\2\2\u019c\u019d\7~\2\2\u019d8\3\2\2\2\u019e")
        buf.write(u"\u019f\7^\2\2\u019f\u01a0\7n\2\2\u01a0\u01a1\7g\2\2\u01a1")
        buf.write(u"\u01a2\7h\2\2\u01a2\u01a3\7v\2\2\u01a3\u01a4\7~\2\2\u01a4")
        buf.write(u":\3\2\2\2\u01a5\u01a6\7^\2\2\u01a6\u01a7\7n\2\2\u01a7")
        buf.write(u"\u01a8\7c\2\2\u01a8\u01a9\7p\2\2\u01a9\u01aa\7i\2\2\u01aa")
        buf.write(u"\u01ab\7n\2\2\u01ab\u01ac\7g\2\2\u01ac<\3\2\2\2\u01ad")
        buf.write(u"\u01ae\7^\2\2\u01ae\u01af\7t\2\2\u01af\u01b0\7c\2\2\u01b0")
        buf.write(u"\u01b1\7p\2\2\u01b1\u01b2\7i\2\2\u01b2\u01b3\7n\2\2\u01b3")
        buf.write(u"\u01b4\7g\2\2\u01b4>\3\2\2\2\u01b5\u01b6\7^\2\2\u01b6")
        buf.write(u"\u01b7\7n\2\2\u01b7\u01b8\7k\2\2\u01b8\u01b9\7o\2\2\u01b9")
        buf.write(u"@\3\2\2\2\u01ba\u01bb\7^\2\2\u01bb\u01bc\7v\2\2\u01bc")
        buf.write(u"\u01f2\7q\2\2\u01bd\u01be\7^\2\2\u01be\u01bf\7t\2\2\u01bf")
        buf.write(u"\u01c0\7k\2\2\u01c0\u01c1\7i\2\2\u01c1\u01c2\7j\2\2\u01c2")
        buf.write(u"\u01c3\7v\2\2\u01c3\u01c4\7c\2\2\u01c4\u01c5\7t\2\2\u01c5")
        buf.write(u"\u01c6\7t\2\2\u01c6\u01c7\7q\2\2\u01c7\u01f2\7y\2\2\u01c8")
        buf.write(u"\u01c9\7^\2\2\u01c9\u01ca\7T\2\2\u01ca\u01cb\7k\2\2\u01cb")
        buf.write(u"\u01cc\7i\2\2\u01cc\u01cd\7j\2\2\u01cd\u01ce\7v\2\2\u01ce")
        buf.write(u"\u01cf\7c\2\2\u01cf\u01d0\7t\2\2\u01d0\u01d1\7t\2\2\u01d1")
        buf.write(u"\u01d2\7q\2\2\u01d2\u01f2\7y\2\2\u01d3\u01d4\7^\2\2\u01d4")
        buf.write(u"\u01d5\7n\2\2\u01d5\u01d6\7q\2\2\u01d6\u01d7\7p\2\2\u01d7")
        buf.write(u"\u01d8\7i\2\2\u01d8\u01d9\7t\2\2\u01d9\u01da\7k\2\2\u01da")
        buf.write(u"\u01db\7i\2\2\u01db\u01dc\7j\2\2\u01dc\u01dd\7v\2\2\u01dd")
        buf.write(u"\u01de\7c\2\2\u01de\u01df\7t\2\2\u01df\u01e0\7t\2\2\u01e0")
        buf.write(u"\u01e1\7q\2\2\u01e1\u01f2\7y\2\2\u01e2\u01e3\7^\2\2\u01e3")
        buf.write(u"\u01e4\7N\2\2\u01e4\u01e5\7q\2\2\u01e5\u01e6\7p\2\2\u01e6")
        buf.write(u"\u01e7\7i\2\2\u01e7\u01e8\7t\2\2\u01e8\u01e9\7k\2\2\u01e9")
        buf.write(u"\u01ea\7i\2\2\u01ea\u01eb\7j\2\2\u01eb\u01ec\7v\2\2\u01ec")
        buf.write(u"\u01ed\7c\2\2\u01ed\u01ee\7t\2\2\u01ee\u01ef\7t\2\2\u01ef")
        buf.write(u"\u01f0\7q\2\2\u01f0\u01f2\7y\2\2\u01f1\u01ba\3\2\2\2")
        buf.write(u"\u01f1\u01bd\3\2\2\2\u01f1\u01c8\3\2\2\2\u01f1\u01d3")
        buf.write(u"\3\2\2\2\u01f1\u01e2\3\2\2\2\u01f2B\3\2\2\2\u01f3\u01f4")
        buf.write(u"\7^\2\2\u01f4\u01f5\7k\2\2\u01f5\u01f6\7p\2\2\u01f6\u01f7")
        buf.write(u"\7v\2\2\u01f7D\3\2\2\2\u01f8\u01f9\7^\2\2\u01f9\u01fa")
        buf.write(u"\7u\2\2\u01fa\u01fb\7w\2\2\u01fb\u0203\7o\2\2\u01fc\u01fd")
        buf.write(u"\7^\2\2\u01fd\u01fe\7U\2\2\u01fe\u01ff\7k\2\2\u01ff\u0200")
        buf.write(u"\7i\2\2\u0200\u0201\7o\2\2\u0201\u0203\7c\2\2\u0202\u01f8")
        buf.write(u"\3\2\2\2\u0202\u01fc\3\2\2\2\u0203F\3\2\2\2\u0204\u0205")
        buf.write(u"\7^\2\2\u0205\u0206\7r\2\2\u0206\u0207\7t\2\2\u0207\u0208")
        buf.write(u"\7q\2\2\u0208\u020d\7f\2\2\u0209\u020a\7^\2\2\u020a\u020b")
        buf.write(u"\7R\2\2\u020b\u020d\7k\2\2\u020c\u0204\3\2\2\2\u020c")
        buf.write(u"\u0209\3\2\2\2\u020dH\3\2\2\2\u020e\u020f\7^\2\2\u020f")
        buf.write(u"\u0210\7g\2\2\u0210\u0211\7z\2\2\u0211\u0212\7r\2\2\u0212")
        buf.write(u"J\3\2\2\2\u0213\u0214\7^\2\2\u0214\u0215\7n\2\2\u0215")
        buf.write(u"\u0216\7q\2\2\u0216\u0217\7i\2\2\u0217L\3\2\2\2\u0218")
        buf.write(u"\u0219\7^\2\2\u0219\u021a\7n\2\2\u021a\u021b\7p\2\2\u021b")
        buf.write(u"N\3\2\2\2\u021c\u021d\7^\2\2\u021d\u021e\7u\2\2\u021e")
        buf.write(u"\u021f\7k\2\2\u021f\u0220\7p\2\2\u0220P\3\2\2\2\u0221")
        buf.write(u"\u0222\7^\2\2\u0222\u0223\7e\2\2\u0223\u0224\7q\2\2\u0224")
        buf.write(u"\u0225\7u\2\2\u0225R\3\2\2\2\u0226\u0227\7^\2\2\u0227")
        buf.write(u"\u0228\7v\2\2\u0228\u0229\7c\2\2\u0229\u022a\7p\2\2\u022a")
        buf.write(u"T\3\2\2\2\u022b\u022c\7^\2\2\u022c\u022d\7e\2\2\u022d")
        buf.write(u"\u022e\7u\2\2\u022e\u022f\7e\2\2\u022fV\3\2\2\2\u0230")
        buf.write(u"\u0231\7^\2\2\u0231\u0232\7u\2\2\u0232\u0233\7g\2\2\u0233")
        buf.write(u"\u0234\7e\2\2\u0234X\3\2\2\2\u0235\u0236\7^\2\2\u0236")
        buf.write(u"\u0237\7e\2\2\u0237\u0238\7q\2\2\u0238\u0239\7v\2\2\u0239")
        buf.write(u"Z\3\2\2\2\u023a\u023b\7^\2\2\u023b\u023c\7c\2\2\u023c")
        buf.write(u"\u023d\7t\2\2\u023d\u023e\7e\2\2\u023e\u023f\7u\2\2\u023f")
        buf.write(u"\u0240\7k\2\2\u0240\u0241\7p\2\2\u0241\\\3\2\2\2\u0242")
        buf.write(u"\u0243\7^\2\2\u0243\u0244\7c\2\2\u0244\u0245\7t\2\2\u0245")
        buf.write(u"\u0246\7e\2\2\u0246\u0247\7e\2\2\u0247\u0248\7q\2\2\u0248")
        buf.write(u"\u0249\7u\2\2\u0249^\3\2\2\2\u024a\u024b\7^\2\2\u024b")
        buf.write(u"\u024c\7c\2\2\u024c\u024d\7t\2\2\u024d\u024e\7e\2\2\u024e")
        buf.write(u"\u024f\7v\2\2\u024f\u0250\7c\2\2\u0250\u0251\7p\2\2\u0251")
        buf.write(u"`\3\2\2\2\u0252\u0253\7^\2\2\u0253\u0254\7c\2\2\u0254")
        buf.write(u"\u0255\7t\2\2\u0255\u0256\7e\2\2\u0256\u0257\7e\2\2\u0257")
        buf.write(u"\u0258\7u\2\2\u0258\u0259\7e\2\2\u0259b\3\2\2\2\u025a")
        buf.write(u"\u025b\7^\2\2\u025b\u025c\7c\2\2\u025c\u025d\7t\2\2\u025d")
        buf.write(u"\u025e\7e\2\2\u025e\u025f\7u\2\2\u025f\u0260\7g\2\2\u0260")
        buf.write(u"\u0261\7e\2\2\u0261d\3\2\2\2\u0262\u0263\7^\2\2\u0263")
        buf.write(u"\u0264\7c\2\2\u0264\u0265\7t\2\2\u0265\u0266\7e\2\2\u0266")
        buf.write(u"\u0267\7e\2\2\u0267\u0268\7q\2\2\u0268\u0269\7v\2\2\u0269")
        buf.write(u"f\3\2\2\2\u026a\u026b\7^\2\2\u026b\u026c\7u\2\2\u026c")
        buf.write(u"\u026d\7k\2\2\u026d\u026e\7p\2\2\u026e\u026f\7j\2\2\u026f")
        buf.write(u"h\3\2\2\2\u0270\u0271\7^\2\2\u0271\u0272\7e\2\2\u0272")
        buf.write(u"\u0273\7q\2\2\u0273\u0274\7u\2\2\u0274\u0275\7j\2\2\u0275")
        buf.write(u"j\3\2\2\2\u0276\u0277\7^\2\2\u0277\u0278\7v\2\2\u0278")
        buf.write(u"\u0279\7c\2\2\u0279\u027a\7p\2\2\u027a\u027b\7j\2\2\u027b")
        buf.write(u"l\3\2\2\2\u027c\u027d\7^\2\2\u027d\u027e\7c\2\2\u027e")
        buf.write(u"\u027f\7t\2\2\u027f\u0280\7u\2\2\u0280\u0281\7k\2\2\u0281")
        buf.write(u"\u0282\7p\2\2\u0282\u0283\7j\2\2\u0283n\3\2\2\2\u0284")
        buf.write(u"\u0285\7^\2\2\u0285\u0286\7c\2\2\u0286\u0287\7t\2\2\u0287")
        buf.write(u"\u0288\7e\2\2\u0288\u0289\7q\2\2\u0289\u028a\7u\2\2\u028a")
        buf.write(u"\u028b\7j\2\2\u028bp\3\2\2\2\u028c\u028d\7^\2\2\u028d")
        buf.write(u"\u028e\7c\2\2\u028e\u028f\7t\2\2\u028f\u0290\7v\2\2\u0290")
        buf.write(u"\u0291\7c\2\2\u0291\u0292\7p\2\2\u0292\u0293\7j\2\2\u0293")
        buf.write(u"r\3\2\2\2\u0294\u0295\7^\2\2\u0295\u0296\7n\2\2\u0296")
        buf.write(u"\u0297\7h\2\2\u0297\u0298\7n\2\2\u0298\u0299\7q\2\2\u0299")
        buf.write(u"\u029a\7q\2\2\u029a\u029b\7t\2\2\u029bt\3\2\2\2\u029c")
        buf.write(u"\u029d\7^\2\2\u029d\u029e\7t\2\2\u029e\u029f\7h\2\2\u029f")
        buf.write(u"\u02a0\7n\2\2\u02a0\u02a1\7q\2\2\u02a1\u02a2\7q\2\2\u02a2")
        buf.write(u"\u02a3\7t\2\2\u02a3v\3\2\2\2\u02a4\u02a5\7^\2\2\u02a5")
        buf.write(u"\u02a6\7n\2\2\u02a6\u02a7\7e\2\2\u02a7\u02a8\7g\2\2\u02a8")
        buf.write(u"\u02a9\7k\2\2\u02a9\u02aa\7n\2\2\u02aax\3\2\2\2\u02ab")
        buf.write(u"\u02ac\7^\2\2\u02ac\u02ad\7t\2\2\u02ad\u02ae\7e\2\2\u02ae")
        buf.write(u"\u02af\7g\2\2\u02af\u02b0\7k\2\2\u02b0\u02b1\7n\2\2\u02b1")
        buf.write(u"z\3\2\2\2\u02b2\u02b3\7^\2\2\u02b3\u02b4\7u\2\2\u02b4")
        buf.write(u"\u02b5\7s\2\2\u02b5\u02b6\7t\2\2\u02b6\u02b7\7v\2\2\u02b7")
        buf.write(u"|\3\2\2\2\u02b8\u02b9\7^\2\2\u02b9\u02ba\7v\2\2\u02ba")
        buf.write(u"\u02bb\7k\2\2\u02bb\u02bc\7o\2\2\u02bc\u02bd\7g\2\2\u02bd")
        buf.write(u"\u02be\7u\2\2\u02be~\3\2\2\2\u02bf\u02c0\7^\2\2\u02c0")
        buf.write(u"\u02c1\7e\2\2\u02c1\u02c2\7f\2\2\u02c2\u02c3\7q\2\2\u02c3")
        buf.write(u"\u02c4\7v\2\2\u02c4\u0080\3\2\2\2\u02c5\u02c6\7^\2\2")
        buf.write(u"\u02c6\u02c7\7f\2\2\u02c7\u02c8\7k\2\2\u02c8\u02c9\7")
        buf.write(u"x\2\2\u02c9\u0082\3\2\2\2\u02ca\u02cb\7^\2\2\u02cb\u02cc")
        buf.write(u"\7h\2\2\u02cc\u02cd\7t\2\2\u02cd\u02ce\7c\2\2\u02ce\u02cf")
        buf.write(u"\7e\2\2\u02cf\u0084\3\2\2\2\u02d0\u02d1\7^\2\2\u02d1")
        buf.write(u"\u02d2\7d\2\2\u02d2\u02d3\7k\2\2\u02d3\u02d4\7p\2\2\u02d4")
        buf.write(u"\u02d5\7q\2\2\u02d5\u02d6\7o\2\2\u02d6\u0086\3\2\2\2")
        buf.write(u"\u02d7\u02d8\7^\2\2\u02d8\u02d9\7f\2\2\u02d9\u02da\7")
        buf.write(u"d\2\2\u02da\u02db\7k\2\2\u02db\u02dc\7p\2\2\u02dc\u02dd")
        buf.write(u"\7q\2\2\u02dd\u02de\7o\2\2\u02de\u0088\3\2\2\2\u02df")
        buf.write(u"\u02e0\7^\2\2\u02e0\u02e1\7v\2\2\u02e1\u02e2\7d\2\2\u02e2")
        buf.write(u"\u02e3\7k\2\2\u02e3\u02e4\7p\2\2\u02e4\u02e5\7q\2\2\u02e5")
        buf.write(u"\u02e6\7o\2\2\u02e6\u008a\3\2\2\2\u02e7\u02e8\7^\2\2")
        buf.write(u"\u02e8\u02e9\7o\2\2\u02e9\u02ea\7c\2\2\u02ea\u02eb\7")
        buf.write(u"v\2\2\u02eb\u02ec\7j\2\2\u02ec\u02ed\7k\2\2\u02ed\u02ee")
        buf.write(u"\7v\2\2\u02ee\u008c\3\2\2\2\u02ef\u02f0\7a\2\2\u02f0")
        buf.write(u"\u008e\3\2\2\2\u02f1\u02f2\7`\2\2\u02f2\u0090\3\2\2\2")
        buf.write(u"\u02f3\u02f4\7<\2\2\u02f4\u0092\3\2\2\2\u02f5\u02f6\t")
        buf.write(u"\2\2\2\u02f6\u0094\3\2\2\2\u02f7\u02fb\7f\2\2\u02f8\u02fa")
        buf.write(u"\5\u0093J\2\u02f9\u02f8\3\2\2\2\u02fa\u02fd\3\2\2\2\u02fb")
        buf.write(u"\u02fc\3\2\2\2\u02fb\u02f9\3\2\2\2\u02fc\u0305\3\2\2")
        buf.write(u"\2\u02fd\u02fb\3\2\2\2\u02fe\u0306\t\3\2\2\u02ff\u0301")
        buf.write(u"\7^\2\2\u0300\u0302\t\3\2\2\u0301\u0300\3\2\2\2\u0302")
        buf.write(u"\u0303\3\2\2\2\u0303\u0301\3\2\2\2\u0303\u0304\3\2\2")
        buf.write(u"\2\u0304\u0306\3\2\2\2\u0305\u02fe\3\2\2\2\u0305\u02ff")
        buf.write(u"\3\2\2\2\u0306\u0096\3\2\2\2\u0307\u0308\t\3\2\2\u0308")
        buf.write(u"\u0098\3\2\2\2\u0309\u030a\t\4\2\2\u030a\u009a\3\2\2")
        buf.write(u"\2\u030b\u030d\5\u0099M\2\u030c\u030b\3\2\2\2\u030d\u030e")
        buf.write(u"\3\2\2\2\u030e\u030c\3\2\2\2\u030e\u030f\3\2\2\2\u030f")
        buf.write(u"\u0317\3\2\2\2\u0310\u0311\7.\2\2\u0311\u0312\5\u0099")
        buf.write(u"M\2\u0312\u0313\5\u0099M\2\u0313\u0314\5\u0099M\2\u0314")
        buf.write(u"\u0316\3\2\2\2\u0315\u0310\3\2\2\2\u0316\u0319\3\2\2")
        buf.write(u"\2\u0317\u0315\3\2\2\2\u0317\u0318\3\2\2\2\u0318\u0331")
        buf.write(u"\3\2\2\2\u0319\u0317\3\2\2\2\u031a\u031c\5\u0099M\2\u031b")
        buf.write(u"\u031a\3\2\2\2\u031c\u031f\3\2\2\2\u031d\u031b\3\2\2")
        buf.write(u"\2\u031d\u031e\3\2\2\2\u031e\u0327\3\2\2\2\u031f\u031d")
        buf.write(u"\3\2\2\2\u0320\u0321\7.\2\2\u0321\u0322\5\u0099M\2\u0322")
        buf.write(u"\u0323\5\u0099M\2\u0323\u0324\5\u0099M\2\u0324\u0326")
        buf.write(u"\3\2\2\2\u0325\u0320\3\2\2\2\u0326\u0329\3\2\2\2\u0327")
        buf.write(u"\u0325\3\2\2\2\u0327\u0328\3\2\2\2\u0328\u032a\3\2\2")
        buf.write(u"\2\u0329\u0327\3\2\2\2\u032a\u032c\7\60\2\2\u032b\u032d")
        buf.write(u"\5\u0099M\2\u032c\u032b\3\2\2\2\u032d\u032e\3\2\2\2\u032e")
        buf.write(u"\u032c\3\2\2\2\u032e\u032f\3\2\2\2\u032f\u0331\3\2\2")
        buf.write(u"\2\u0330\u030c\3\2\2\2\u0330\u031d\3\2\2\2\u0331\u009c")
        buf.write(u"\3\2\2\2\u0332\u0336\7(\2\2\u0333\u0335\5\u0093J\2\u0334")
        buf.write(u"\u0333\3\2\2\2\u0335\u0338\3\2\2\2\u0336\u0337\3\2\2")
        buf.write(u"\2\u0336\u0334\3\2\2\2\u0337\u033a\3\2\2\2\u0338\u0336")
        buf.write(u"\3\2\2\2\u0339\u0332\3\2\2\2\u0339\u033a\3\2\2\2\u033a")
        buf.write(u"\u033b\3\2\2\2\u033b\u0347\7?\2\2\u033c\u0344\7?\2\2")
        buf.write(u"\u033d\u033f\5\u0093J\2\u033e\u033d\3\2\2\2\u033f\u0342")
        buf.write(u"\3\2\2\2\u0340\u0341\3\2\2\2\u0340\u033e\3\2\2\2\u0341")
        buf.write(u"\u0343\3\2\2\2\u0342\u0340\3\2\2\2\u0343\u0345\7(\2\2")
        buf.write(u"\u0344\u0340\3\2\2\2\u0344\u0345\3\2\2\2\u0345\u0347")
        buf.write(u"\3\2\2\2\u0346\u0339\3\2\2\2\u0346\u033c\3\2\2\2\u0347")
        buf.write(u"\u009e\3\2\2\2\u0348\u0349\7^\2\2\u0349\u034a\7p\2\2")
        buf.write(u"\u034a\u034b\7g\2\2\u034b\u034c\7s\2\2\u034c\u00a0\3")
        buf.write(u"\2\2\2\u034d\u034e\7>\2\2\u034e\u00a2\3\2\2\2\u034f\u0350")
        buf.write(u"\7^\2\2\u0350\u0351\7n\2\2\u0351\u0352\7g\2\2\u0352\u0359")
        buf.write(u"\7s\2\2\u0353\u0354\7^\2\2\u0354\u0355\7n\2\2\u0355\u0359")
        buf.write(u"\7g\2\2\u0356\u0359\5\u00a5S\2\u0357\u0359\5\u00a7T\2")
        buf.write(u"\u0358\u034f\3\2\2\2\u0358\u0353\3\2\2\2\u0358\u0356")
        buf.write(u"\3\2\2\2\u0358\u0357\3\2\2\2\u0359\u00a4\3\2\2\2\u035a")
        buf.write(u"\u035b\7^\2\2\u035b\u035c\7n\2\2\u035c\u035d\7g\2\2\u035d")
        buf.write(u"\u035e\7s\2\2\u035e\u035f\7s\2\2\u035f\u00a6\3\2\2\2")
        buf.write(u"\u0360\u0361\7^\2\2\u0361\u0362\7n\2\2\u0362\u0363\7")
        buf.write(u"g\2\2\u0363\u0364\7s\2\2\u0364\u0365\7u\2\2\u0365\u0366")
        buf.write(u"\7n\2\2\u0366\u0367\7c\2\2\u0367\u0368\7p\2\2\u0368\u0369")
        buf.write(u"\7v\2\2\u0369\u00a8\3\2\2\2\u036a\u036b\7@\2\2\u036b")
        buf.write(u"\u00aa\3\2\2\2\u036c\u036d\7^\2\2\u036d\u036e\7i\2\2")
        buf.write(u"\u036e\u036f\7g\2\2\u036f\u0376\7s\2\2\u0370\u0371\7")
        buf.write(u"^\2\2\u0371\u0372\7i\2\2\u0372\u0376\7g\2\2\u0373\u0376")
        buf.write(u"\5\u00adW\2\u0374\u0376\5\u00afX\2\u0375\u036c\3\2\2")
        buf.write(u"\2\u0375\u0370\3\2\2\2\u0375\u0373\3\2\2\2\u0375\u0374")
        buf.write(u"\3\2\2\2\u0376\u00ac\3\2\2\2\u0377\u0378\7^\2\2\u0378")
        buf.write(u"\u0379\7i\2\2\u0379\u037a\7g\2\2\u037a\u037b\7s\2\2\u037b")
        buf.write(u"\u037c\7s\2\2\u037c\u00ae\3\2\2\2\u037d\u037e\7^\2\2")
        buf.write(u"\u037e\u037f\7i\2\2\u037f\u0380\7g\2\2\u0380\u0381\7")
        buf.write(u"s\2\2\u0381\u0382\7u\2\2\u0382\u0383\7n\2\2\u0383\u0384")
        buf.write(u"\7c\2\2\u0384\u0385\7p\2\2\u0385\u0386\7v\2\2\u0386\u00b0")
        buf.write(u"\3\2\2\2\u0387\u0388\7#\2\2\u0388\u00b2\3\2\2\2\u0389")
        buf.write(u"\u038b\7^\2\2\u038a\u038c\t\3\2\2\u038b\u038a\3\2\2\2")
        buf.write(u"\u038c\u038d\3\2\2\2\u038d\u038b\3\2\2\2\u038d\u038e")
        buf.write(u"\3\2\2\2\u038e\u00b4\3\2\2\2\35\2\u00ba\u00ca\u00d9\u00ea")
        buf.write(u"\u010e\u0176\u01f1\u0202\u020c\u02fb\u0303\u0305\u030e")
        buf.write(u"\u0317\u031d\u0327\u032e\u0330\u0336\u0339\u0340\u0344")
        buf.write(u"\u0346\u0358\u0375\u038d\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    THINSPACE = 3
    MEDSPACE = 4
    THICKSPACE = 5
    QUAD = 6
    QQUAD = 7
    NEGTHINSPACE = 8
    NEGMEDSPACE = 9
    NEGTHICKSPACE = 10
    CMD_LEFT = 11
    CMD_RIGHT = 12
    IGNORE = 13
    ADD = 14
    SUB = 15
    MUL = 16
    DIV = 17
    L_PAREN = 18
    R_PAREN = 19
    L_BRACE = 20
    R_BRACE = 21
    L_BRACE_LITERAL = 22
    R_BRACE_LITERAL = 23
    L_BRACKET = 24
    R_BRACKET = 25
    BAR = 26
    R_BAR = 27
    L_BAR = 28
    L_ANGLE = 29
    R_ANGLE = 30
    FUNC_LIM = 31
    LIM_APPROACH_SYM = 32
    FUNC_INT = 33
    FUNC_SUM = 34
    FUNC_PROD = 35
    FUNC_EXP = 36
    FUNC_LOG = 37
    FUNC_LN = 38
    FUNC_SIN = 39
    FUNC_COS = 40
    FUNC_TAN = 41
    FUNC_CSC = 42
    FUNC_SEC = 43
    FUNC_COT = 44
    FUNC_ARCSIN = 45
    FUNC_ARCCOS = 46
    FUNC_ARCTAN = 47
    FUNC_ARCCSC = 48
    FUNC_ARCSEC = 49
    FUNC_ARCCOT = 50
    FUNC_SINH = 51
    FUNC_COSH = 52
    FUNC_TANH = 53
    FUNC_ARSINH = 54
    FUNC_ARCOSH = 55
    FUNC_ARTANH = 56
    L_FLOOR = 57
    R_FLOOR = 58
    L_CEIL = 59
    R_CEIL = 60
    FUNC_SQRT = 61
    CMD_TIMES = 62
    CMD_CDOT = 63
    CMD_DIV = 64
    CMD_FRAC = 65
    CMD_BINOM = 66
    CMD_DBINOM = 67
    CMD_TBINOM = 68
    CMD_MATHIT = 69
    UNDERSCORE = 70
    CARET = 71
    COLON = 72
    DIFFERENTIAL = 73
    LETTER = 74
    NUMBER = 75
    EQUAL = 76
    NEQ = 77
    LT = 78
    LTE = 79
    LTE_Q = 80
    LTE_S = 81
    GT = 82
    GTE = 83
    GTE_Q = 84
    GTE_S = 85
    BANG = 86
    SYMBOL = 87

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ u"DEFAULT_MODE" ]

    literalNames = [ u"<INVALID>",
            u"','", u"'\\quad'", u"'\\qquad'", u"'\\negmedspace'", u"'\\negthickspace'",
            u"'\\left'", u"'\\right'", u"'+'", u"'-'", u"'*'", u"'/'", u"'('",
            u"')'", u"'{'", u"'}'", u"'\\{'", u"'\\}'", u"'['", u"']'",
            u"'|'", u"'\\right|'", u"'\\left|'", u"'\\langle'", u"'\\rangle'",
            u"'\\lim'", u"'\\int'", u"'\\exp'", u"'\\log'", u"'\\ln'", u"'\\sin'",
            u"'\\cos'", u"'\\tan'", u"'\\csc'", u"'\\sec'", u"'\\cot'",
            u"'\\arcsin'", u"'\\arccos'", u"'\\arctan'", u"'\\arccsc'",
            u"'\\arcsec'", u"'\\arccot'", u"'\\sinh'", u"'\\cosh'", u"'\\tanh'",
            u"'\\arsinh'", u"'\\arcosh'", u"'\\artanh'", u"'\\lfloor'",
            u"'\\rfloor'", u"'\\lceil'", u"'\\rceil'", u"'\\sqrt'", u"'\\times'",
            u"'\\cdot'", u"'\\div'", u"'\\frac'", u"'\\binom'", u"'\\dbinom'",
            u"'\\tbinom'", u"'\\mathit'", u"'_'", u"'^'", u"':'", u"'\\neq'",
            u"'<'", u"'\\leqq'", u"'\\leqslant'", u"'>'", u"'\\geqq'", u"'\\geqslant'",
            u"'!'" ]

    symbolicNames = [ u"<INVALID>",
            u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE", u"QUAD", u"QQUAD",
            u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE", u"CMD_LEFT",
            u"CMD_RIGHT", u"IGNORE", u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN",
            u"R_PAREN", u"L_BRACE", u"R_BRACE", u"L_BRACE_LITERAL", u"R_BRACE_LITERAL",
            u"L_BRACKET", u"R_BRACKET", u"BAR", u"R_BAR", u"L_BAR", u"L_ANGLE",
            u"R_ANGLE", u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT", u"FUNC_SUM",
            u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG", u"FUNC_LN", u"FUNC_SIN",
            u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC", u"FUNC_COT",
            u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN", u"FUNC_ARCCSC",
            u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH", u"FUNC_COSH",
            u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH", u"FUNC_ARTANH",
            u"L_FLOOR", u"R_FLOOR", u"L_CEIL", u"R_CEIL", u"FUNC_SQRT",
            u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC", u"CMD_BINOM",
            u"CMD_DBINOM", u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE",
            u"CARET", u"COLON", u"DIFFERENTIAL", u"LETTER", u"NUMBER", u"EQUAL",
            u"NEQ", u"LT", u"LTE", u"LTE_Q", u"LTE_S", u"GT", u"GTE", u"GTE_Q",
            u"GTE_S", u"BANG", u"SYMBOL" ]

    ruleNames = [ u"T__0", u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE",
                  u"QUAD", u"QQUAD", u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE",
                  u"CMD_LEFT", u"CMD_RIGHT", u"IGNORE", u"ADD", u"SUB",
                  u"MUL", u"DIV", u"L_PAREN", u"R_PAREN", u"L_BRACE", u"R_BRACE",
                  u"L_BRACE_LITERAL", u"R_BRACE_LITERAL", u"L_BRACKET",
                  u"R_BRACKET", u"BAR", u"R_BAR", u"L_BAR", u"L_ANGLE",
                  u"R_ANGLE", u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT",
                  u"FUNC_SUM", u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG", u"FUNC_LN",
                  u"FUNC_SIN", u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC",
                  u"FUNC_COT", u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN",
                  u"FUNC_ARCCSC", u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH",
                  u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH",
                  u"FUNC_ARTANH", u"L_FLOOR", u"R_FLOOR", u"L_CEIL", u"R_CEIL",
                  u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV", u"CMD_FRAC",
                  u"CMD_BINOM", u"CMD_DBINOM", u"CMD_TBINOM", u"CMD_MATHIT",
                  u"UNDERSCORE", u"CARET", u"COLON", u"WS_CHAR", u"DIFFERENTIAL",
                  u"LETTER", u"DIGIT", u"NUMBER", u"EQUAL", u"NEQ", u"LT",
                  u"LTE", u"LTE_Q", u"LTE_S", u"GT", u"GTE", u"GTE_Q", u"GTE_S",
                  u"BANG", u"SYMBOL" ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


