
# encoding: utf-8

# *** GENERATED BY `setup.py antlr`, DO NOT EDIT BY HAND ***
#
# Generated from ../LaTeX.g4, derived from latex2sympy
#     latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
from __future__ import print_function
from antlr4 import *
from io import StringIO
import sys



def serializedATN():
    with StringIO() as buf:
        buf.write(u"\3\u608b\ua72a\u8133\ub9ed\u417c\u3be7\u7786\u5964\2")
        buf.write(u"P\u02e8\b\1\4\2\t\2\4\3\t\3\4\4\t\4\4\5\t\5\4\6\t\6\4")
        buf.write(u"\7\t\7\4\b\t\b\4\t\t\t\4\n\t\n\4\13\t\13\4\f\t\f\4\r")
        buf.write(u"\t\r\4\16\t\16\4\17\t\17\4\20\t\20\4\21\t\21\4\22\t\22")
        buf.write(u"\4\23\t\23\4\24\t\24\4\25\t\25\4\26\t\26\4\27\t\27\4")
        buf.write(u"\30\t\30\4\31\t\31\4\32\t\32\4\33\t\33\4\34\t\34\4\35")
        buf.write(u"\t\35\4\36\t\36\4\37\t\37\4 \t \4!\t!\4\"\t\"\4#\t#\4")
        buf.write(u"$\t$\4%\t%\4&\t&\4\'\t\'\4(\t(\4)\t)\4*\t*\4+\t+\4,\t")
        buf.write(u",\4-\t-\4.\t.\4/\t/\4\60\t\60\4\61\t\61\4\62\t\62\4\63")
        buf.write(u"\t\63\4\64\t\64\4\65\t\65\4\66\t\66\4\67\t\67\48\t8\4")
        buf.write(u"9\t9\4:\t:\4;\t;\4<\t<\4=\t=\4>\t>\4?\t?\4@\t@\4A\tA")
        buf.write(u"\4B\tB\4C\tC\4D\tD\4E\tE\4F\tF\4G\tG\4H\tH\4I\tI\4J\t")
        buf.write(u"J\4K\tK\4L\tL\4M\tM\4N\tN\4O\tO\4P\tP\4Q\tQ\3\2\3\2\3")
        buf.write(u"\3\6\3\u00a7\n\3\r\3\16\3\u00a8\3\3\3\3\3\4\3\4\3\4\3")
        buf.write(u"\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\3\4\5\4\u00b9\n\4\3\4")
        buf.write(u"\3\4\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\3\5\5\5")
        buf.write(u"\u00c8\n\5\3\5\3\5\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3\6\3")
        buf.write(u"\6\3\6\3\6\3\6\3\6\5\6\u00d9\n\6\3\6\3\6\3\7\3\7\3\7")
        buf.write(u"\3\7\3\7\3\7\3\7\3\7\3\b\3\b\3\b\3\b\3\b\3\b\3\b\3\b")
        buf.write(u"\3\b\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t\3\t")
        buf.write(u"\3\t\3\t\3\t\5\t\u00fd\n\t\3\t\3\t\3\n\3\n\3\n\3\n\3")
        buf.write(u"\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\n\3\13\3\13")
        buf.write(u"\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3\13\3")
        buf.write(u"\13\3\13\3\13\3\13\3\13\3\f\3\f\3\r\3\r\3\16\3\16\3\17")
        buf.write(u"\3\17\3\20\3\20\3\21\3\21\3\22\3\22\3\23\3\23\3\24\3")
        buf.write(u"\24\3\24\3\25\3\25\3\25\3\26\3\26\3\27\3\27\3\30\3\30")
        buf.write(u"\3\30\3\30\3\30\3\30\3\30\3\30\3\31\3\31\3\31\3\31\3")
        buf.write(u"\31\3\31\3\31\3\31\3\31\3\32\3\32\3\33\3\33\3\33\3\33")
        buf.write(u"\3\33\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34")
        buf.write(u"\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34")
        buf.write(u"\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3\34\3")
        buf.write(u"\34\3\34\3\34\3\34\5\34\u018a\n\34\3\35\3\35\3\35\3\35")
        buf.write(u"\3\35\3\36\3\36\3\36\3\36\3\36\3\37\3\37\3\37\3\37\3")
        buf.write(u"\37\3\37\3 \3 \3 \3 \3 \3!\3!\3!\3!\3!\3\"\3\"\3\"\3")
        buf.write(u"\"\3#\3#\3#\3#\3#\3$\3$\3$\3$\3$\3%\3%\3%\3%\3%\3&\3")
        buf.write(u"&\3&\3&\3&\3\'\3\'\3\'\3\'\3\'\3(\3(\3(\3(\3(\3)\3)\3")
        buf.write(u")\3)\3)\3)\3)\3)\3*\3*\3*\3*\3*\3*\3*\3*\3+\3+\3+\3+")
        buf.write(u"\3+\3+\3+\3+\3,\3,\3,\3,\3,\3,\3,\3,\3-\3-\3-\3-\3-\3")
        buf.write(u"-\3-\3-\3.\3.\3.\3.\3.\3.\3.\3.\3/\3/\3/\3/\3/\3/\3\60")
        buf.write(u"\3\60\3\60\3\60\3\60\3\60\3\61\3\61\3\61\3\61\3\61\3")
        buf.write(u"\61\3\62\3\62\3\62\3\62\3\62\3\62\3\62\3\62\3\63\3\63")
        buf.write(u"\3\63\3\63\3\63\3\63\3\63\3\63\3\64\3\64\3\64\3\64\3")
        buf.write(u"\64\3\64\3\64\3\64\3\65\3\65\3\65\3\65\3\65\3\65\3\66")
        buf.write(u"\3\66\3\66\3\66\3\66\3\66\3\66\3\67\3\67\3\67\3\67\3")
        buf.write(u"\67\3\67\38\38\38\38\38\39\39\39\39\39\39\3:\3:\3:\3")
        buf.write(u":\3:\3:\3:\3;\3;\3;\3;\3;\3;\3;\3;\3<\3<\3<\3<\3<\3<")
        buf.write(u"\3<\3<\3=\3=\3=\3=\3=\3=\3=\3=\3>\3>\3?\3?\3@\3@\3A\3")
        buf.write(u"A\3B\3B\7B\u0269\nB\fB\16B\u026c\13B\3B\3B\3B\6B\u0271")
        buf.write(u"\nB\rB\16B\u0272\5B\u0275\nB\3C\3C\3D\3D\3E\6E\u027c")
        buf.write(u"\nE\rE\16E\u027d\3E\3E\3E\3E\3E\7E\u0285\nE\fE\16E\u0288")
        buf.write(u"\13E\3E\7E\u028b\nE\fE\16E\u028e\13E\3E\3E\3E\3E\3E\7")
        buf.write(u"E\u0295\nE\fE\16E\u0298\13E\3E\3E\6E\u029c\nE\rE\16E")
        buf.write(u"\u029d\5E\u02a0\nE\3F\3F\3G\3G\3G\3G\3G\3H\3H\3I\3I\3")
        buf.write(u"I\3I\3I\3I\3I\3I\5I\u02b3\nI\3J\3J\3J\3J\3J\3J\3K\3K")
        buf.write(u"\3K\3K\3K\3K\3K\3K\3K\3K\3L\3L\3M\3M\3M\3M\3M\3M\3M\3")
        buf.write(u"M\5M\u02cf\nM\3N\3N\3N\3N\3N\3N\3O\3O\3O\3O\3O\3O\3O")
        buf.write(u"\3O\3O\3O\3P\3P\3Q\3Q\6Q\u02e5\nQ\rQ\16Q\u02e6\3\u026a")
        buf.write(u"\2R\3\3\5\4\7\5\t\6\13\7\r\b\17\t\21\n\23\13\25\f\27")
        buf.write(u"\r\31\16\33\17\35\20\37\21!\22#\23%\24\'\25)\26+\27-")
        buf.write(u"\30/\31\61\32\63\33\65\34\67\359\36;\37= ?!A\"C#E$G%")
        buf.write(u"I&K\'M(O)Q*S+U,W-Y.[/]\60_\61a\62c\63e\64g\65i\66k\67")
        buf.write(u"m8o9q:s;u<w=y>{?}@\177A\u0081\2\u0083B\u0085C\u0087\2")
        buf.write(u"\u0089D\u008bE\u008dF\u008fG\u0091H\u0093I\u0095J\u0097")
        buf.write(u"K\u0099L\u009bM\u009dN\u009fO\u00a1P\3\2\5\5\2\13\f\17")
        buf.write(u"\17\"\"\4\2C\\c|\3\2\62;\2\u02fe\2\3\3\2\2\2\2\5\3\2")
        buf.write(u"\2\2\2\7\3\2\2\2\2\t\3\2\2\2\2\13\3\2\2\2\2\r\3\2\2\2")
        buf.write(u"\2\17\3\2\2\2\2\21\3\2\2\2\2\23\3\2\2\2\2\25\3\2\2\2")
        buf.write(u"\2\27\3\2\2\2\2\31\3\2\2\2\2\33\3\2\2\2\2\35\3\2\2\2")
        buf.write(u"\2\37\3\2\2\2\2!\3\2\2\2\2#\3\2\2\2\2%\3\2\2\2\2\'\3")
        buf.write(u"\2\2\2\2)\3\2\2\2\2+\3\2\2\2\2-\3\2\2\2\2/\3\2\2\2\2")
        buf.write(u"\61\3\2\2\2\2\63\3\2\2\2\2\65\3\2\2\2\2\67\3\2\2\2\2")
        buf.write(u"9\3\2\2\2\2;\3\2\2\2\2=\3\2\2\2\2?\3\2\2\2\2A\3\2\2\2")
        buf.write(u"\2C\3\2\2\2\2E\3\2\2\2\2G\3\2\2\2\2I\3\2\2\2\2K\3\2\2")
        buf.write(u"\2\2M\3\2\2\2\2O\3\2\2\2\2Q\3\2\2\2\2S\3\2\2\2\2U\3\2")
        buf.write(u"\2\2\2W\3\2\2\2\2Y\3\2\2\2\2[\3\2\2\2\2]\3\2\2\2\2_\3")
        buf.write(u"\2\2\2\2a\3\2\2\2\2c\3\2\2\2\2e\3\2\2\2\2g\3\2\2\2\2")
        buf.write(u"i\3\2\2\2\2k\3\2\2\2\2m\3\2\2\2\2o\3\2\2\2\2q\3\2\2\2")
        buf.write(u"\2s\3\2\2\2\2u\3\2\2\2\2w\3\2\2\2\2y\3\2\2\2\2{\3\2\2")
        buf.write(u"\2\2}\3\2\2\2\2\177\3\2\2\2\2\u0083\3\2\2\2\2\u0085\3")
        buf.write(u"\2\2\2\2\u0089\3\2\2\2\2\u008b\3\2\2\2\2\u008d\3\2\2")
        buf.write(u"\2\2\u008f\3\2\2\2\2\u0091\3\2\2\2\2\u0093\3\2\2\2\2")
        buf.write(u"\u0095\3\2\2\2\2\u0097\3\2\2\2\2\u0099\3\2\2\2\2\u009b")
        buf.write(u"\3\2\2\2\2\u009d\3\2\2\2\2\u009f\3\2\2\2\2\u00a1\3\2")
        buf.write(u"\2\2\3\u00a3\3\2\2\2\5\u00a6\3\2\2\2\7\u00b8\3\2\2\2")
        buf.write(u"\t\u00c7\3\2\2\2\13\u00d8\3\2\2\2\r\u00dc\3\2\2\2\17")
        buf.write(u"\u00e4\3\2\2\2\21\u00fc\3\2\2\2\23\u0100\3\2\2\2\25\u010f")
        buf.write(u"\3\2\2\2\27\u0120\3\2\2\2\31\u0122\3\2\2\2\33\u0124\3")
        buf.write(u"\2\2\2\35\u0126\3\2\2\2\37\u0128\3\2\2\2!\u012a\3\2\2")
        buf.write(u"\2#\u012c\3\2\2\2%\u012e\3\2\2\2\'\u0130\3\2\2\2)\u0133")
        buf.write(u"\3\2\2\2+\u0136\3\2\2\2-\u0138\3\2\2\2/\u013a\3\2\2\2")
        buf.write(u"\61\u0142\3\2\2\2\63\u014b\3\2\2\2\65\u014d\3\2\2\2\67")
        buf.write(u"\u0189\3\2\2\29\u018b\3\2\2\2;\u0190\3\2\2\2=\u0195\3")
        buf.write(u"\2\2\2?\u019b\3\2\2\2A\u01a0\3\2\2\2C\u01a5\3\2\2\2E")
        buf.write(u"\u01a9\3\2\2\2G\u01ae\3\2\2\2I\u01b3\3\2\2\2K\u01b8\3")
        buf.write(u"\2\2\2M\u01bd\3\2\2\2O\u01c2\3\2\2\2Q\u01c7\3\2\2\2S")
        buf.write(u"\u01cf\3\2\2\2U\u01d7\3\2\2\2W\u01df\3\2\2\2Y\u01e7\3")
        buf.write(u"\2\2\2[\u01ef\3\2\2\2]\u01f7\3\2\2\2_\u01fd\3\2\2\2a")
        buf.write(u"\u0203\3\2\2\2c\u0209\3\2\2\2e\u0211\3\2\2\2g\u0219\3")
        buf.write(u"\2\2\2i\u0221\3\2\2\2k\u0227\3\2\2\2m\u022e\3\2\2\2o")
        buf.write(u"\u0234\3\2\2\2q\u0239\3\2\2\2s\u023f\3\2\2\2u\u0246\3")
        buf.write(u"\2\2\2w\u024e\3\2\2\2y\u0256\3\2\2\2{\u025e\3\2\2\2}")
        buf.write(u"\u0260\3\2\2\2\177\u0262\3\2\2\2\u0081\u0264\3\2\2\2")
        buf.write(u"\u0083\u0266\3\2\2\2\u0085\u0276\3\2\2\2\u0087\u0278")
        buf.write(u"\3\2\2\2\u0089\u029f\3\2\2\2\u008b\u02a1\3\2\2\2\u008d")
        buf.write(u"\u02a3\3\2\2\2\u008f\u02a8\3\2\2\2\u0091\u02b2\3\2\2")
        buf.write(u"\2\u0093\u02b4\3\2\2\2\u0095\u02ba\3\2\2\2\u0097\u02c4")
        buf.write(u"\3\2\2\2\u0099\u02ce\3\2\2\2\u009b\u02d0\3\2\2\2\u009d")
        buf.write(u"\u02d6\3\2\2\2\u009f\u02e0\3\2\2\2\u00a1\u02e2\3\2\2")
        buf.write(u"\2\u00a3\u00a4\7.\2\2\u00a4\4\3\2\2\2\u00a5\u00a7\t\2")
        buf.write(u"\2\2\u00a6\u00a5\3\2\2\2\u00a7\u00a8\3\2\2\2\u00a8\u00a6")
        buf.write(u"\3\2\2\2\u00a8\u00a9\3\2\2\2\u00a9\u00aa\3\2\2\2\u00aa")
        buf.write(u"\u00ab\b\3\2\2\u00ab\6\3\2\2\2\u00ac\u00ad\7^\2\2\u00ad")
        buf.write(u"\u00b9\7.\2\2\u00ae\u00af\7^\2\2\u00af\u00b0\7v\2\2\u00b0")
        buf.write(u"\u00b1\7j\2\2\u00b1\u00b2\7k\2\2\u00b2\u00b3\7p\2\2\u00b3")
        buf.write(u"\u00b4\7u\2\2\u00b4\u00b5\7r\2\2\u00b5\u00b6\7c\2\2\u00b6")
        buf.write(u"\u00b7\7e\2\2\u00b7\u00b9\7g\2\2\u00b8\u00ac\3\2\2\2")
        buf.write(u"\u00b8\u00ae\3\2\2\2\u00b9\u00ba\3\2\2\2\u00ba\u00bb")
        buf.write(u"\b\4\2\2\u00bb\b\3\2\2\2\u00bc\u00bd\7^\2\2\u00bd\u00c8")
        buf.write(u"\7<\2\2\u00be\u00bf\7^\2\2\u00bf\u00c0\7o\2\2\u00c0\u00c1")
        buf.write(u"\7g\2\2\u00c1\u00c2\7f\2\2\u00c2\u00c3\7u\2\2\u00c3\u00c4")
        buf.write(u"\7r\2\2\u00c4\u00c5\7c\2\2\u00c5\u00c6\7e\2\2\u00c6\u00c8")
        buf.write(u"\7g\2\2\u00c7\u00bc\3\2\2\2\u00c7\u00be\3\2\2\2\u00c8")
        buf.write(u"\u00c9\3\2\2\2\u00c9\u00ca\b\5\2\2\u00ca\n\3\2\2\2\u00cb")
        buf.write(u"\u00cc\7^\2\2\u00cc\u00d9\7=\2\2\u00cd\u00ce\7^\2\2\u00ce")
        buf.write(u"\u00cf\7v\2\2\u00cf\u00d0\7j\2\2\u00d0\u00d1\7k\2\2\u00d1")
        buf.write(u"\u00d2\7e\2\2\u00d2\u00d3\7m\2\2\u00d3\u00d4\7u\2\2\u00d4")
        buf.write(u"\u00d5\7r\2\2\u00d5\u00d6\7c\2\2\u00d6\u00d7\7e\2\2\u00d7")
        buf.write(u"\u00d9\7g\2\2\u00d8\u00cb\3\2\2\2\u00d8\u00cd\3\2\2\2")
        buf.write(u"\u00d9\u00da\3\2\2\2\u00da\u00db\b\6\2\2\u00db\f\3\2")
        buf.write(u"\2\2\u00dc\u00dd\7^\2\2\u00dd\u00de\7s\2\2\u00de\u00df")
        buf.write(u"\7w\2\2\u00df\u00e0\7c\2\2\u00e0\u00e1\7f\2\2\u00e1\u00e2")
        buf.write(u"\3\2\2\2\u00e2\u00e3\b\7\2\2\u00e3\16\3\2\2\2\u00e4\u00e5")
        buf.write(u"\7^\2\2\u00e5\u00e6\7s\2\2\u00e6\u00e7\7s\2\2\u00e7\u00e8")
        buf.write(u"\7w\2\2\u00e8\u00e9\7c\2\2\u00e9\u00ea\7f\2\2\u00ea\u00eb")
        buf.write(u"\3\2\2\2\u00eb\u00ec\b\b\2\2\u00ec\20\3\2\2\2\u00ed\u00ee")
        buf.write(u"\7^\2\2\u00ee\u00fd\7#\2\2\u00ef\u00f0\7^\2\2\u00f0\u00f1")
        buf.write(u"\7p\2\2\u00f1\u00f2\7g\2\2\u00f2\u00f3\7i\2\2\u00f3\u00f4")
        buf.write(u"\7v\2\2\u00f4\u00f5\7j\2\2\u00f5\u00f6\7k\2\2\u00f6\u00f7")
        buf.write(u"\7p\2\2\u00f7\u00f8\7u\2\2\u00f8\u00f9\7r\2\2\u00f9\u00fa")
        buf.write(u"\7c\2\2\u00fa\u00fb\7e\2\2\u00fb\u00fd\7g\2\2\u00fc\u00ed")
        buf.write(u"\3\2\2\2\u00fc\u00ef\3\2\2\2\u00fd\u00fe\3\2\2\2\u00fe")
        buf.write(u"\u00ff\b\t\2\2\u00ff\22\3\2\2\2\u0100\u0101\7^\2\2\u0101")
        buf.write(u"\u0102\7p\2\2\u0102\u0103\7g\2\2\u0103\u0104\7i\2\2\u0104")
        buf.write(u"\u0105\7o\2\2\u0105\u0106\7g\2\2\u0106\u0107\7f\2\2\u0107")
        buf.write(u"\u0108\7u\2\2\u0108\u0109\7r\2\2\u0109\u010a\7c\2\2\u010a")
        buf.write(u"\u010b\7e\2\2\u010b\u010c\7g\2\2\u010c\u010d\3\2\2\2")
        buf.write(u"\u010d\u010e\b\n\2\2\u010e\24\3\2\2\2\u010f\u0110\7^")
        buf.write(u"\2\2\u0110\u0111\7p\2\2\u0111\u0112\7g\2\2\u0112\u0113")
        buf.write(u"\7i\2\2\u0113\u0114\7v\2\2\u0114\u0115\7j\2\2\u0115\u0116")
        buf.write(u"\7k\2\2\u0116\u0117\7e\2\2\u0117\u0118\7m\2\2\u0118\u0119")
        buf.write(u"\7u\2\2\u0119\u011a\7r\2\2\u011a\u011b\7c\2\2\u011b\u011c")
        buf.write(u"\7e\2\2\u011c\u011d\7g\2\2\u011d\u011e\3\2\2\2\u011e")
        buf.write(u"\u011f\b\13\2\2\u011f\26\3\2\2\2\u0120\u0121\7-\2\2\u0121")
        buf.write(u"\30\3\2\2\2\u0122\u0123\7/\2\2\u0123\32\3\2\2\2\u0124")
        buf.write(u"\u0125\7,\2\2\u0125\34\3\2\2\2\u0126\u0127\7\61\2\2\u0127")
        buf.write(u"\36\3\2\2\2\u0128\u0129\7*\2\2\u0129 \3\2\2\2\u012a\u012b")
        buf.write(u"\7+\2\2\u012b\"\3\2\2\2\u012c\u012d\7}\2\2\u012d$\3\2")
        buf.write(u"\2\2\u012e\u012f\7\177\2\2\u012f&\3\2\2\2\u0130\u0131")
        buf.write(u"\7^\2\2\u0131\u0132\7}\2\2\u0132(\3\2\2\2\u0133\u0134")
        buf.write(u"\7^\2\2\u0134\u0135\7\177\2\2\u0135*\3\2\2\2\u0136\u0137")
        buf.write(u"\7]\2\2\u0137,\3\2\2\2\u0138\u0139\7_\2\2\u0139.\3\2")
        buf.write(u"\2\2\u013a\u013b\7^\2\2\u013b\u013c\7n\2\2\u013c\u013d")
        buf.write(u"\7g\2\2\u013d\u013e\7h\2\2\u013e\u013f\7v\2\2\u013f\u0140")
        buf.write(u"\3\2\2\2\u0140\u0141\b\30\2\2\u0141\60\3\2\2\2\u0142")
        buf.write(u"\u0143\7^\2\2\u0143\u0144\7t\2\2\u0144\u0145\7k\2\2\u0145")
        buf.write(u"\u0146\7i\2\2\u0146\u0147\7j\2\2\u0147\u0148\7v\2\2\u0148")
        buf.write(u"\u0149\3\2\2\2\u0149\u014a\b\31\2\2\u014a\62\3\2\2\2")
        buf.write(u"\u014b\u014c\7~\2\2\u014c\64\3\2\2\2\u014d\u014e\7^\2")
        buf.write(u"\2\u014e\u014f\7n\2\2\u014f\u0150\7k\2\2\u0150\u0151")
        buf.write(u"\7o\2\2\u0151\66\3\2\2\2\u0152\u0153\7^\2\2\u0153\u0154")
        buf.write(u"\7v\2\2\u0154\u018a\7q\2\2\u0155\u0156\7^\2\2\u0156\u0157")
        buf.write(u"\7t\2\2\u0157\u0158\7k\2\2\u0158\u0159\7i\2\2\u0159\u015a")
        buf.write(u"\7j\2\2\u015a\u015b\7v\2\2\u015b\u015c\7c\2\2\u015c\u015d")
        buf.write(u"\7t\2\2\u015d\u015e\7t\2\2\u015e\u015f\7q\2\2\u015f\u018a")
        buf.write(u"\7y\2\2\u0160\u0161\7^\2\2\u0161\u0162\7T\2\2\u0162\u0163")
        buf.write(u"\7k\2\2\u0163\u0164\7i\2\2\u0164\u0165\7j\2\2\u0165\u0166")
        buf.write(u"\7v\2\2\u0166\u0167\7c\2\2\u0167\u0168\7t\2\2\u0168\u0169")
        buf.write(u"\7t\2\2\u0169\u016a\7q\2\2\u016a\u018a\7y\2\2\u016b\u016c")
        buf.write(u"\7^\2\2\u016c\u016d\7n\2\2\u016d\u016e\7q\2\2\u016e\u016f")
        buf.write(u"\7p\2\2\u016f\u0170\7i\2\2\u0170\u0171\7t\2\2\u0171\u0172")
        buf.write(u"\7k\2\2\u0172\u0173\7i\2\2\u0173\u0174\7j\2\2\u0174\u0175")
        buf.write(u"\7v\2\2\u0175\u0176\7c\2\2\u0176\u0177\7t\2\2\u0177\u0178")
        buf.write(u"\7t\2\2\u0178\u0179\7q\2\2\u0179\u018a\7y\2\2\u017a\u017b")
        buf.write(u"\7^\2\2\u017b\u017c\7N\2\2\u017c\u017d\7q\2\2\u017d\u017e")
        buf.write(u"\7p\2\2\u017e\u017f\7i\2\2\u017f\u0180\7t\2\2\u0180\u0181")
        buf.write(u"\7k\2\2\u0181\u0182\7i\2\2\u0182\u0183\7j\2\2\u0183\u0184")
        buf.write(u"\7v\2\2\u0184\u0185\7c\2\2\u0185\u0186\7t\2\2\u0186\u0187")
        buf.write(u"\7t\2\2\u0187\u0188\7q\2\2\u0188\u018a\7y\2\2\u0189\u0152")
        buf.write(u"\3\2\2\2\u0189\u0155\3\2\2\2\u0189\u0160\3\2\2\2\u0189")
        buf.write(u"\u016b\3\2\2\2\u0189\u017a\3\2\2\2\u018a8\3\2\2\2\u018b")
        buf.write(u"\u018c\7^\2\2\u018c\u018d\7k\2\2\u018d\u018e\7p\2\2\u018e")
        buf.write(u"\u018f\7v\2\2\u018f:\3\2\2\2\u0190\u0191\7^\2\2\u0191")
        buf.write(u"\u0192\7u\2\2\u0192\u0193\7w\2\2\u0193\u0194\7o\2\2\u0194")
        buf.write(u"<\3\2\2\2\u0195\u0196\7^\2\2\u0196\u0197\7r\2\2\u0197")
        buf.write(u"\u0198\7t\2\2\u0198\u0199\7q\2\2\u0199\u019a\7f\2\2\u019a")
        buf.write(u">\3\2\2\2\u019b\u019c\7^\2\2\u019c\u019d\7g\2\2\u019d")
        buf.write(u"\u019e\7z\2\2\u019e\u019f\7r\2\2\u019f@\3\2\2\2\u01a0")
        buf.write(u"\u01a1\7^\2\2\u01a1\u01a2\7n\2\2\u01a2\u01a3\7q\2\2\u01a3")
        buf.write(u"\u01a4\7i\2\2\u01a4B\3\2\2\2\u01a5\u01a6\7^\2\2\u01a6")
        buf.write(u"\u01a7\7n\2\2\u01a7\u01a8\7p\2\2\u01a8D\3\2\2\2\u01a9")
        buf.write(u"\u01aa\7^\2\2\u01aa\u01ab\7u\2\2\u01ab\u01ac\7k\2\2\u01ac")
        buf.write(u"\u01ad\7p\2\2\u01adF\3\2\2\2\u01ae\u01af\7^\2\2\u01af")
        buf.write(u"\u01b0\7e\2\2\u01b0\u01b1\7q\2\2\u01b1\u01b2\7u\2\2\u01b2")
        buf.write(u"H\3\2\2\2\u01b3\u01b4\7^\2\2\u01b4\u01b5\7v\2\2\u01b5")
        buf.write(u"\u01b6\7c\2\2\u01b6\u01b7\7p\2\2\u01b7J\3\2\2\2\u01b8")
        buf.write(u"\u01b9\7^\2\2\u01b9\u01ba\7e\2\2\u01ba\u01bb\7u\2\2\u01bb")
        buf.write(u"\u01bc\7e\2\2\u01bcL\3\2\2\2\u01bd\u01be\7^\2\2\u01be")
        buf.write(u"\u01bf\7u\2\2\u01bf\u01c0\7g\2\2\u01c0\u01c1\7e\2\2\u01c1")
        buf.write(u"N\3\2\2\2\u01c2\u01c3\7^\2\2\u01c3\u01c4\7e\2\2\u01c4")
        buf.write(u"\u01c5\7q\2\2\u01c5\u01c6\7v\2\2\u01c6P\3\2\2\2\u01c7")
        buf.write(u"\u01c8\7^\2\2\u01c8\u01c9\7c\2\2\u01c9\u01ca\7t\2\2\u01ca")
        buf.write(u"\u01cb\7e\2\2\u01cb\u01cc\7u\2\2\u01cc\u01cd\7k\2\2\u01cd")
        buf.write(u"\u01ce\7p\2\2\u01ceR\3\2\2\2\u01cf\u01d0\7^\2\2\u01d0")
        buf.write(u"\u01d1\7c\2\2\u01d1\u01d2\7t\2\2\u01d2\u01d3\7e\2\2\u01d3")
        buf.write(u"\u01d4\7e\2\2\u01d4\u01d5\7q\2\2\u01d5\u01d6\7u\2\2\u01d6")
        buf.write(u"T\3\2\2\2\u01d7\u01d8\7^\2\2\u01d8\u01d9\7c\2\2\u01d9")
        buf.write(u"\u01da\7t\2\2\u01da\u01db\7e\2\2\u01db\u01dc\7v\2\2\u01dc")
        buf.write(u"\u01dd\7c\2\2\u01dd\u01de\7p\2\2\u01deV\3\2\2\2\u01df")
        buf.write(u"\u01e0\7^\2\2\u01e0\u01e1\7c\2\2\u01e1\u01e2\7t\2\2\u01e2")
        buf.write(u"\u01e3\7e\2\2\u01e3\u01e4\7e\2\2\u01e4\u01e5\7u\2\2\u01e5")
        buf.write(u"\u01e6\7e\2\2\u01e6X\3\2\2\2\u01e7\u01e8\7^\2\2\u01e8")
        buf.write(u"\u01e9\7c\2\2\u01e9\u01ea\7t\2\2\u01ea\u01eb\7e\2\2\u01eb")
        buf.write(u"\u01ec\7u\2\2\u01ec\u01ed\7g\2\2\u01ed\u01ee\7e\2\2\u01ee")
        buf.write(u"Z\3\2\2\2\u01ef\u01f0\7^\2\2\u01f0\u01f1\7c\2\2\u01f1")
        buf.write(u"\u01f2\7t\2\2\u01f2\u01f3\7e\2\2\u01f3\u01f4\7e\2\2\u01f4")
        buf.write(u"\u01f5\7q\2\2\u01f5\u01f6\7v\2\2\u01f6\\\3\2\2\2\u01f7")
        buf.write(u"\u01f8\7^\2\2\u01f8\u01f9\7u\2\2\u01f9\u01fa\7k\2\2\u01fa")
        buf.write(u"\u01fb\7p\2\2\u01fb\u01fc\7j\2\2\u01fc^\3\2\2\2\u01fd")
        buf.write(u"\u01fe\7^\2\2\u01fe\u01ff\7e\2\2\u01ff\u0200\7q\2\2\u0200")
        buf.write(u"\u0201\7u\2\2\u0201\u0202\7j\2\2\u0202`\3\2\2\2\u0203")
        buf.write(u"\u0204\7^\2\2\u0204\u0205\7v\2\2\u0205\u0206\7c\2\2\u0206")
        buf.write(u"\u0207\7p\2\2\u0207\u0208\7j\2\2\u0208b\3\2\2\2\u0209")
        buf.write(u"\u020a\7^\2\2\u020a\u020b\7c\2\2\u020b\u020c\7t\2\2\u020c")
        buf.write(u"\u020d\7u\2\2\u020d\u020e\7k\2\2\u020e\u020f\7p\2\2\u020f")
        buf.write(u"\u0210\7j\2\2\u0210d\3\2\2\2\u0211\u0212\7^\2\2\u0212")
        buf.write(u"\u0213\7c\2\2\u0213\u0214\7t\2\2\u0214\u0215\7e\2\2\u0215")
        buf.write(u"\u0216\7q\2\2\u0216\u0217\7u\2\2\u0217\u0218\7j\2\2\u0218")
        buf.write(u"f\3\2\2\2\u0219\u021a\7^\2\2\u021a\u021b\7c\2\2\u021b")
        buf.write(u"\u021c\7t\2\2\u021c\u021d\7v\2\2\u021d\u021e\7c\2\2\u021e")
        buf.write(u"\u021f\7p\2\2\u021f\u0220\7j\2\2\u0220h\3\2\2\2\u0221")
        buf.write(u"\u0222\7^\2\2\u0222\u0223\7u\2\2\u0223\u0224\7s\2\2\u0224")
        buf.write(u"\u0225\7t\2\2\u0225\u0226\7v\2\2\u0226j\3\2\2\2\u0227")
        buf.write(u"\u0228\7^\2\2\u0228\u0229\7v\2\2\u0229\u022a\7k\2\2\u022a")
        buf.write(u"\u022b\7o\2\2\u022b\u022c\7g\2\2\u022c\u022d\7u\2\2\u022d")
        buf.write(u"l\3\2\2\2\u022e\u022f\7^\2\2\u022f\u0230\7e\2\2\u0230")
        buf.write(u"\u0231\7f\2\2\u0231\u0232\7q\2\2\u0232\u0233\7v\2\2\u0233")
        buf.write(u"n\3\2\2\2\u0234\u0235\7^\2\2\u0235\u0236\7f\2\2\u0236")
        buf.write(u"\u0237\7k\2\2\u0237\u0238\7x\2\2\u0238p\3\2\2\2\u0239")
        buf.write(u"\u023a\7^\2\2\u023a\u023b\7h\2\2\u023b\u023c\7t\2\2\u023c")
        buf.write(u"\u023d\7c\2\2\u023d\u023e\7e\2\2\u023er\3\2\2\2\u023f")
        buf.write(u"\u0240\7^\2\2\u0240\u0241\7d\2\2\u0241\u0242\7k\2\2\u0242")
        buf.write(u"\u0243\7p\2\2\u0243\u0244\7q\2\2\u0244\u0245\7o\2\2\u0245")
        buf.write(u"t\3\2\2\2\u0246\u0247\7^\2\2\u0247\u0248\7f\2\2\u0248")
        buf.write(u"\u0249\7d\2\2\u0249\u024a\7k\2\2\u024a\u024b\7p\2\2\u024b")
        buf.write(u"\u024c\7q\2\2\u024c\u024d\7o\2\2\u024dv\3\2\2\2\u024e")
        buf.write(u"\u024f\7^\2\2\u024f\u0250\7v\2\2\u0250\u0251\7d\2\2\u0251")
        buf.write(u"\u0252\7k\2\2\u0252\u0253\7p\2\2\u0253\u0254\7q\2\2\u0254")
        buf.write(u"\u0255\7o\2\2\u0255x\3\2\2\2\u0256\u0257\7^\2\2\u0257")
        buf.write(u"\u0258\7o\2\2\u0258\u0259\7c\2\2\u0259\u025a\7v\2\2\u025a")
        buf.write(u"\u025b\7j\2\2\u025b\u025c\7k\2\2\u025c\u025d\7v\2\2\u025d")
        buf.write(u"z\3\2\2\2\u025e\u025f\7a\2\2\u025f|\3\2\2\2\u0260\u0261")
        buf.write(u"\7`\2\2\u0261~\3\2\2\2\u0262\u0263\7<\2\2\u0263\u0080")
        buf.write(u"\3\2\2\2\u0264\u0265\t\2\2\2\u0265\u0082\3\2\2\2\u0266")
        buf.write(u"\u026a\7f\2\2\u0267\u0269\5\u0081A\2\u0268\u0267\3\2")
        buf.write(u"\2\2\u0269\u026c\3\2\2\2\u026a\u026b\3\2\2\2\u026a\u0268")
        buf.write(u"\3\2\2\2\u026b\u0274\3\2\2\2\u026c\u026a\3\2\2\2\u026d")
        buf.write(u"\u0275\t\3\2\2\u026e\u0270\7^\2\2\u026f\u0271\t\3\2\2")
        buf.write(u"\u0270\u026f\3\2\2\2\u0271\u0272\3\2\2\2\u0272\u0270")
        buf.write(u"\3\2\2\2\u0272\u0273\3\2\2\2\u0273\u0275\3\2\2\2\u0274")
        buf.write(u"\u026d\3\2\2\2\u0274\u026e\3\2\2\2\u0275\u0084\3\2\2")
        buf.write(u"\2\u0276\u0277\t\3\2\2\u0277\u0086\3\2\2\2\u0278\u0279")
        buf.write(u"\t\4\2\2\u0279\u0088\3\2\2\2\u027a\u027c\5\u0087D\2\u027b")
        buf.write(u"\u027a\3\2\2\2\u027c\u027d\3\2\2\2\u027d\u027b\3\2\2")
        buf.write(u"\2\u027d\u027e\3\2\2\2\u027e\u0286\3\2\2\2\u027f\u0280")
        buf.write(u"\7.\2\2\u0280\u0281\5\u0087D\2\u0281\u0282\5\u0087D\2")
        buf.write(u"\u0282\u0283\5\u0087D\2\u0283\u0285\3\2\2\2\u0284\u027f")
        buf.write(u"\3\2\2\2\u0285\u0288\3\2\2\2\u0286\u0284\3\2\2\2\u0286")
        buf.write(u"\u0287\3\2\2\2\u0287\u02a0\3\2\2\2\u0288\u0286\3\2\2")
        buf.write(u"\2\u0289\u028b\5\u0087D\2\u028a\u0289\3\2\2\2\u028b\u028e")
        buf.write(u"\3\2\2\2\u028c\u028a\3\2\2\2\u028c\u028d\3\2\2\2\u028d")
        buf.write(u"\u0296\3\2\2\2\u028e\u028c\3\2\2\2\u028f\u0290\7.\2\2")
        buf.write(u"\u0290\u0291\5\u0087D\2\u0291\u0292\5\u0087D\2\u0292")
        buf.write(u"\u0293\5\u0087D\2\u0293\u0295\3\2\2\2\u0294\u028f\3\2")
        buf.write(u"\2\2\u0295\u0298\3\2\2\2\u0296\u0294\3\2\2\2\u0296\u0297")
        buf.write(u"\3\2\2\2\u0297\u0299\3\2\2\2\u0298\u0296\3\2\2\2\u0299")
        buf.write(u"\u029b\7\60\2\2\u029a\u029c\5\u0087D\2\u029b\u029a\3")
        buf.write(u"\2\2\2\u029c\u029d\3\2\2\2\u029d\u029b\3\2\2\2\u029d")
        buf.write(u"\u029e\3\2\2\2\u029e\u02a0\3\2\2\2\u029f\u027b\3\2\2")
        buf.write(u"\2\u029f\u028c\3\2\2\2\u02a0\u008a\3\2\2\2\u02a1\u02a2")
        buf.write(u"\7?\2\2\u02a2\u008c\3\2\2\2\u02a3\u02a4\7^\2\2\u02a4")
        buf.write(u"\u02a5\7p\2\2\u02a5\u02a6\7g\2\2\u02a6\u02a7\7s\2\2\u02a7")
        buf.write(u"\u008e\3\2\2\2\u02a8\u02a9\7>\2\2\u02a9\u0090\3\2\2\2")
        buf.write(u"\u02aa\u02ab\7^\2\2\u02ab\u02ac\7n\2\2\u02ac\u02ad\7")
        buf.write(u"g\2\2\u02ad\u02b3\7s\2\2\u02ae\u02af\7n\2\2\u02af\u02b3")
        buf.write(u"\7g\2\2\u02b0\u02b3\5\u0093J\2\u02b1\u02b3\5\u0095K\2")
        buf.write(u"\u02b2\u02aa\3\2\2\2\u02b2\u02ae\3\2\2\2\u02b2\u02b0")
        buf.write(u"\3\2\2\2\u02b2\u02b1\3\2\2\2\u02b3\u0092\3\2\2\2\u02b4")
        buf.write(u"\u02b5\7^\2\2\u02b5\u02b6\7n\2\2\u02b6\u02b7\7g\2\2\u02b7")
        buf.write(u"\u02b8\7s\2\2\u02b8\u02b9\7s\2\2\u02b9\u0094\3\2\2\2")
        buf.write(u"\u02ba\u02bb\7^\2\2\u02bb\u02bc\7n\2\2\u02bc\u02bd\7")
        buf.write(u"g\2\2\u02bd\u02be\7s\2\2\u02be\u02bf\7u\2\2\u02bf\u02c0")
        buf.write(u"\7n\2\2\u02c0\u02c1\7c\2\2\u02c1\u02c2\7p\2\2\u02c2\u02c3")
        buf.write(u"\7v\2\2\u02c3\u0096\3\2\2\2\u02c4\u02c5\7@\2\2\u02c5")
        buf.write(u"\u0098\3\2\2\2\u02c6\u02c7\7^\2\2\u02c7\u02c8\7i\2\2")
        buf.write(u"\u02c8\u02c9\7g\2\2\u02c9\u02cf\7s\2\2\u02ca\u02cb\7")
        buf.write(u"i\2\2\u02cb\u02cf\7g\2\2\u02cc\u02cf\5\u009bN\2\u02cd")
        buf.write(u"\u02cf\5\u009dO\2\u02ce\u02c6\3\2\2\2\u02ce\u02ca\3\2")
        buf.write(u"\2\2\u02ce\u02cc\3\2\2\2\u02ce\u02cd\3\2\2\2\u02cf\u009a")
        buf.write(u"\3\2\2\2\u02d0\u02d1\7^\2\2\u02d1\u02d2\7i\2\2\u02d2")
        buf.write(u"\u02d3\7g\2\2\u02d3\u02d4\7s\2\2\u02d4\u02d5\7s\2\2\u02d5")
        buf.write(u"\u009c\3\2\2\2\u02d6\u02d7\7^\2\2\u02d7\u02d8\7i\2\2")
        buf.write(u"\u02d8\u02d9\7g\2\2\u02d9\u02da\7s\2\2\u02da\u02db\7")
        buf.write(u"u\2\2\u02db\u02dc\7n\2\2\u02dc\u02dd\7c\2\2\u02dd\u02de")
        buf.write(u"\7p\2\2\u02de\u02df\7v\2\2\u02df\u009e\3\2\2\2\u02e0")
        buf.write(u"\u02e1\7#\2\2\u02e1\u00a0\3\2\2\2\u02e2\u02e4\7^\2\2")
        buf.write(u"\u02e3\u02e5\t\3\2\2\u02e4\u02e3\3\2\2\2\u02e5\u02e6")
        buf.write(u"\3\2\2\2\u02e6\u02e4\3\2\2\2\u02e6\u02e7\3\2\2\2\u02e7")
        buf.write(u"\u00a2\3\2\2\2\25\2\u00a8\u00b8\u00c7\u00d8\u00fc\u0189")
        buf.write(u"\u026a\u0272\u0274\u027d\u0286\u028c\u0296\u029d\u029f")
        buf.write(u"\u02b2\u02ce\u02e6\3\b\2\2")
        return buf.getvalue()


class LaTeXLexer(Lexer):

    atn = ATNDeserializer().deserialize(serializedATN())

    decisionsToDFA = [ DFA(ds, i) for i, ds in enumerate(atn.decisionToState) ]

    T__0 = 1
    WS = 2
    THINSPACE = 3
    MEDSPACE = 4
    THICKSPACE = 5
    QUAD = 6
    QQUAD = 7
    NEGTHINSPACE = 8
    NEGMEDSPACE = 9
    NEGTHICKSPACE = 10
    ADD = 11
    SUB = 12
    MUL = 13
    DIV = 14
    L_PAREN = 15
    R_PAREN = 16
    L_BRACE = 17
    R_BRACE = 18
    L_BRACE_LITERAL = 19
    R_BRACE_LITERAL = 20
    L_BRACKET = 21
    R_BRACKET = 22
    CMD_LEFT = 23
    CMD_RIGHT = 24
    BAR = 25
    FUNC_LIM = 26
    LIM_APPROACH_SYM = 27
    FUNC_INT = 28
    FUNC_SUM = 29
    FUNC_PROD = 30
    FUNC_EXP = 31
    FUNC_LOG = 32
    FUNC_LN = 33
    FUNC_SIN = 34
    FUNC_COS = 35
    FUNC_TAN = 36
    FUNC_CSC = 37
    FUNC_SEC = 38
    FUNC_COT = 39
    FUNC_ARCSIN = 40
    FUNC_ARCCOS = 41
    FUNC_ARCTAN = 42
    FUNC_ARCCSC = 43
    FUNC_ARCSEC = 44
    FUNC_ARCCOT = 45
    FUNC_SINH = 46
    FUNC_COSH = 47
    FUNC_TANH = 48
    FUNC_ARSINH = 49
    FUNC_ARCOSH = 50
    FUNC_ARTANH = 51
    FUNC_SQRT = 52
    CMD_TIMES = 53
    CMD_CDOT = 54
    CMD_DIV = 55
    CMD_FRAC = 56
    CMD_BINOM = 57
    CMD_DBINOM = 58
    CMD_TBINOM = 59
    CMD_MATHIT = 60
    UNDERSCORE = 61
    CARET = 62
    COLON = 63
    DIFFERENTIAL = 64
    LETTER = 65
    NUMBER = 66
    EQUAL = 67
    NEQ = 68
    LT = 69
    LTE = 70
    LTE_Q = 71
    LTE_S = 72
    GT = 73
    GTE = 74
    GTE_Q = 75
    GTE_S = 76
    BANG = 77
    SYMBOL = 78

    channelNames = [ u"DEFAULT_TOKEN_CHANNEL", u"HIDDEN" ]

    modeNames = [ u"DEFAULT_MODE" ]

    literalNames = [ u"<INVALID>",
            u"','", u"'\\quad'", u"'\\qquad'", u"'\\negmedspace'", u"'\\negthickspace'",
            u"'+'", u"'-'", u"'*'", u"'/'", u"'('", u"')'", u"'{'", u"'}'",
            u"'\\{'", u"'\\}'", u"'['", u"']'", u"'\\left'", u"'\\right'",
            u"'|'", u"'\\lim'", u"'\\int'", u"'\\sum'", u"'\\prod'", u"'\\exp'",
            u"'\\log'", u"'\\ln'", u"'\\sin'", u"'\\cos'", u"'\\tan'", u"'\\csc'",
            u"'\\sec'", u"'\\cot'", u"'\\arcsin'", u"'\\arccos'", u"'\\arctan'",
            u"'\\arccsc'", u"'\\arcsec'", u"'\\arccot'", u"'\\sinh'", u"'\\cosh'",
            u"'\\tanh'", u"'\\arsinh'", u"'\\arcosh'", u"'\\artanh'", u"'\\sqrt'",
            u"'\\times'", u"'\\cdot'", u"'\\div'", u"'\\frac'", u"'\\binom'",
            u"'\\dbinom'", u"'\\tbinom'", u"'\\mathit'", u"'_'", u"'^'",
            u"':'", u"'='", u"'\\neq'", u"'<'", u"'\\leqq'", u"'\\leqslant'",
            u"'>'", u"'\\geqq'", u"'\\geqslant'", u"'!'" ]

    symbolicNames = [ u"<INVALID>",
            u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE", u"QUAD", u"QQUAD",
            u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE", u"ADD", u"SUB",
            u"MUL", u"DIV", u"L_PAREN", u"R_PAREN", u"L_BRACE", u"R_BRACE",
            u"L_BRACE_LITERAL", u"R_BRACE_LITERAL", u"L_BRACKET", u"R_BRACKET",
            u"CMD_LEFT", u"CMD_RIGHT", u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM",
            u"FUNC_INT", u"FUNC_SUM", u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG",
            u"FUNC_LN", u"FUNC_SIN", u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC",
            u"FUNC_SEC", u"FUNC_COT", u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN",
            u"FUNC_ARCCSC", u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH",
            u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH",
            u"FUNC_ARTANH", u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT", u"CMD_DIV",
            u"CMD_FRAC", u"CMD_BINOM", u"CMD_DBINOM", u"CMD_TBINOM", u"CMD_MATHIT",
            u"UNDERSCORE", u"CARET", u"COLON", u"DIFFERENTIAL", u"LETTER",
            u"NUMBER", u"EQUAL", u"NEQ", u"LT", u"LTE", u"LTE_Q", u"LTE_S",
            u"GT", u"GTE", u"GTE_Q", u"GTE_S", u"BANG", u"SYMBOL" ]

    ruleNames = [ u"T__0", u"WS", u"THINSPACE", u"MEDSPACE", u"THICKSPACE",
                  u"QUAD", u"QQUAD", u"NEGTHINSPACE", u"NEGMEDSPACE", u"NEGTHICKSPACE",
                  u"ADD", u"SUB", u"MUL", u"DIV", u"L_PAREN", u"R_PAREN",
                  u"L_BRACE", u"R_BRACE", u"L_BRACE_LITERAL", u"R_BRACE_LITERAL",
                  u"L_BRACKET", u"R_BRACKET", u"CMD_LEFT", u"CMD_RIGHT",
                  u"BAR", u"FUNC_LIM", u"LIM_APPROACH_SYM", u"FUNC_INT",
                  u"FUNC_SUM", u"FUNC_PROD", u"FUNC_EXP", u"FUNC_LOG", u"FUNC_LN",
                  u"FUNC_SIN", u"FUNC_COS", u"FUNC_TAN", u"FUNC_CSC", u"FUNC_SEC",
                  u"FUNC_COT", u"FUNC_ARCSIN", u"FUNC_ARCCOS", u"FUNC_ARCTAN",
                  u"FUNC_ARCCSC", u"FUNC_ARCSEC", u"FUNC_ARCCOT", u"FUNC_SINH",
                  u"FUNC_COSH", u"FUNC_TANH", u"FUNC_ARSINH", u"FUNC_ARCOSH",
                  u"FUNC_ARTANH", u"FUNC_SQRT", u"CMD_TIMES", u"CMD_CDOT",
                  u"CMD_DIV", u"CMD_FRAC", u"CMD_BINOM", u"CMD_DBINOM",
                  u"CMD_TBINOM", u"CMD_MATHIT", u"UNDERSCORE", u"CARET",
                  u"COLON", u"WS_CHAR", u"DIFFERENTIAL", u"LETTER", u"DIGIT",
                  u"NUMBER", u"EQUAL", u"NEQ", u"LT", u"LTE", u"LTE_Q",
                  u"LTE_S", u"GT", u"GTE", u"GTE_Q", u"GTE_S", u"BANG",
                  u"SYMBOL" ]

    grammarFileName = u"LaTeX.g4"

    def __init__(self, input=None, output=sys.stdout):
        super(LaTeXLexer, self).__init__(input, output=output)
        self.checkVersion("4.7.2")
        self._interp = LexerATNSimulator(self, self.atn, self.decisionsToDFA, PredictionContextCache())
        self._actions = None
        self._predicates = None


