FROM continuumio/anaconda3

WORKDIR /home

RUN apt-get update \
    && apt-get install -y git make zip graphviz inkscape texlive-xetex texlive-fonts-recommended texlive-latex-extra librsvg2-bin docbook2x \
    && apt-get -y clean

RUN conda config --add channels conda-forge
RUN conda config --set always_yes yes
RUN conda create -n sympy-release mpmath python=3.6 rever \
    && conda clean --all
RUN conda info
# Important: every command below should run 'source activate sympy-release &&
# <command>' to be run in the conda environment.

RUN git clone git://github.com/sympy/sympy.git
