"""
Do NOT manually edit this file.
Instead, run ./bin/ask_update.py.
"""

_pre_calculated_assumptions = {'beta_rules': [({('algebraic', False), ('complex', True)},
                 ('transcendental', True)),
                ({('integer', True), ('even', False)}, ('odd', True)),
                ({('integer', True), ('odd', False)}, ('even', True)),
                ({('infinite', False), ('real', False)},
                 ('extended_real', False)),
                ({('extended_real', True), ('infinite', False)},
                 ('real', True)),
                ({('extended_real', True), ('real', False)},
                 ('infinite', True)),
                ({('extended_real', True), ('finite', True)}, ('real', True)),
                ({('extended_negative', False), ('extended_positive', False),
                  ('zero', False)},
                 ('extended_real', False)),
                ({('extended_positive', False), ('extended_real', True),
                  ('zero', False)},
                 ('extended_negative', True)),
                ({('extended_negative', False), ('extended_positive', False),
                  ('extended_real', True)},
                 ('zero', True)),
                ({('extended_negative', False), ('extended_real', True),
                  ('zero', False)},
                 ('extended_positive', True)),
                ({('extended_nonzero', True), ('extended_nonpositive', True)},
                 ('extended_negative', True)),
                ({('extended_nonzero', True), ('extended_nonnegative', True)},
                 ('extended_positive', True)),
                ({('extended_real', True), ('extended_positive', False)},
                 ('extended_nonpositive', True)),
                ({('extended_negative', False), ('extended_real', True)},
                 ('extended_nonnegative', True)),
                ({('zero', False), ('negative', False), ('positive', False)},
                 ('real', False)),
                ({('zero', False), ('real', True), ('positive', False)},
                 ('negative', True)),
                ({('real', True), ('negative', False), ('positive', False)},
                 ('zero', True)),
                ({('zero', False), ('real', True), ('negative', False)},
                 ('positive', True)),
                ({('nonpositive', True), ('nonzero', True)},
                 ('negative', True)),
                ({('nonzero', True), ('nonnegative', True)},
                 ('positive', True)),
                ({('real', True), ('positive', False)}, ('nonpositive', True)),
                ({('real', True), ('negative', False)}, ('nonnegative', True)),
                ({('extended_positive', True), ('finite', True)},
                 ('positive', True)),
                ({('extended_negative', True), ('finite', True)},
                 ('negative', True)),
                ({('finite', True), ('extended_nonpositive', True)},
                 ('nonpositive', True)),
                ({('finite', True), ('extended_nonnegative', True)},
                 ('nonnegative', True)),
                ({('extended_nonzero', True), ('finite', True)},
                 ('nonzero', True)),
                ({('extended_nonnegative', True),
                  ('extended_nonpositive', True)},
                 ('zero', True)),
                ({('nonpositive', True), ('nonnegative', True)},
                 ('zero', True)),
                ({('positive', True), ('even', True), ('prime', False)},
                 ('composite', True)),
                ({('positive', True), ('composite', False), ('prime', False)},
                 ('even', False)),
                ({('positive', True), ('composite', False), ('even', True)},
                 ('prime', True)),
                ({('composite', False), ('even', True), ('prime', False)},
                 ('positive', False)),
                ({('real', True), ('rational', False)}, ('irrational', True)),
                ({('integer', False), ('extended_real', True)},
                 ('noninteger', True)),
                ({('zero', False), ('extended_real', True)},
                 ('extended_nonzero', True))],
 'beta_triggers': {('algebraic', False): [0, 7, 8, 10, 15, 16, 18, 34, 35, 36],
                   ('algebraic', True): [3, 4, 6, 23, 24, 25, 26, 27],
                   ('antihermitian', False): [],
                   ('commutative', False): [],
                   ('complex', False): [3, 5, 7, 8, 10, 35, 36],
                   ('complex', True): [0, 3, 4, 6, 23, 24, 25, 26, 27],
                   ('composite', False): [31, 32, 33],
                   ('composite', True): [1, 2],
                   ('even', False): [1, 7, 8, 10, 15, 16, 18, 36],
                   ('even', True): [8, 9, 10, 13, 14, 16, 17, 18, 21, 22, 23,
                                    24, 25, 26, 27, 30, 32, 33, 36],
                   ('extended_negative', False): [7, 9, 10, 14, 15, 17, 18, 22],
                   ('extended_negative', True): [4, 5, 6, 15, 16, 21, 24, 25,
                                                 27, 35],
                   ('extended_nonnegative', False): [7, 8, 13, 15, 16, 21, 36],
                   ('extended_nonnegative', True): [4, 5, 6, 9, 10, 12, 13, 15,
                                                    17, 18, 22, 26, 28, 35,
                                                    36],
                   ('extended_nonpositive', False): [7, 10, 14, 15, 18, 22, 36],
                   ('extended_nonpositive', True): [4, 5, 6, 8, 9, 11, 14, 15,
                                                    16, 17, 21, 25, 28, 35,
                                                    36],
                   ('extended_nonzero', False): [7, 9, 13, 14, 15, 17, 21, 22],
                   ('extended_nonzero', True): [4, 5, 6, 8, 10, 11, 12, 13, 14,
                                                15, 16, 18, 27, 35],
                   ('extended_positive', False): [7, 8, 9, 13, 15, 16, 17, 21],
                   ('extended_positive', True): [4, 5, 6, 15, 18, 22, 23, 26,
                                                 27, 35],
                   ('extended_real', False): [],
                   ('extended_real', True): [4, 5, 6, 8, 9, 10, 13, 14, 35, 36],
                   ('finite', False): [7, 8, 10, 35, 36],
                   ('finite', True): [3, 4, 6, 23, 24, 25, 26, 27],
                   ('hermitian', False): [3, 5, 7, 8, 10, 35, 36],
                   ('imaginary', True): [0],
                   ('infinite', False): [3, 4, 6, 23, 24, 25, 26, 27],
                   ('infinite', True): [7, 8, 10, 35, 36],
                   ('integer', False): [7, 8, 10, 15, 16, 18, 35, 36],
                   ('integer', True): [1, 2, 8, 9, 10, 13, 14, 16, 17, 18, 21,
                                       22, 23, 24, 25, 26, 27, 36],
                   ('irrational', True): [0, 8, 10, 11, 12, 13, 14, 16, 18, 19,
                                          20, 21, 22, 23, 24, 25, 26],
                   ('negative', False): [15, 17, 18, 22],
                   ('negative', True): [0, 34, 35],
                   ('noninteger', True): [4, 5, 6, 8, 10, 11, 12, 13, 14, 15,
                                          16, 18, 27],
                   ('nonnegative', False): [7, 8, 10, 15, 16, 21, 36],
                   ('nonnegative', True): [0, 9, 10, 12, 13, 17, 18, 20, 21, 23,
                                           25, 27, 28, 29, 34, 35, 36],
                   ('nonpositive', False): [7, 8, 10, 15, 18, 22, 36],
                   ('nonpositive', True): [0, 8, 9, 11, 14, 16, 17, 19, 22, 24,
                                           26, 27, 28, 29, 34, 35, 36],
                   ('nonzero', False): [15, 17, 21, 22],
                   ('nonzero', True): [0, 8, 10, 11, 12, 13, 14, 16, 18, 19, 20,
                                       21, 22, 23, 24, 25, 26, 34, 35],
                   ('odd', False): [2],
                   ('odd', True): [8, 10, 11, 12, 13, 14, 16, 18, 19, 20, 21,
                                   22, 23, 24, 25, 26],
                   ('positive', False): [15, 16, 17, 21],
                   ('positive', True): [0, 30, 31, 32, 34, 35],
                   ('prime', False): [30, 31, 33],
                   ('prime', True): [1, 2],
                   ('rational', False): [7, 8, 10, 15, 16, 18, 34, 35, 36],
                   ('rational', True): [8, 9, 10, 13, 14, 16, 17, 18, 21, 22,
                                        23, 24, 25, 26, 27, 35, 36],
                   ('real', False): [3, 5, 7, 8, 10, 35, 36],
                   ('real', True): [0, 8, 9, 10, 13, 14, 16, 17, 18, 21, 22, 23,
                                    24, 25, 26, 27, 34, 35, 36],
                   ('transcendental', True): [3, 4, 6, 7, 8, 10, 15, 16, 18, 23,
                                              24, 25, 26, 27, 34, 35, 36],
                   ('zero', False): [7, 8, 10, 15, 16, 18, 36],
                   ('zero', True): []},
 'defined_facts': ['algebraic', 'antihermitian', 'commutative', 'complex',
                   'composite', 'even', 'extended_negative',
                   'extended_nonnegative', 'extended_nonpositive',
                   'extended_nonzero', 'extended_positive', 'extended_real',
                   'finite', 'hermitian', 'imaginary', 'infinite', 'integer',
                   'irrational', 'negative', 'noninteger', 'nonnegative',
                   'nonpositive', 'nonzero', 'odd', 'positive', 'prime',
                   'rational', 'real', 'transcendental', 'zero'],
 'full_implications': {('algebraic', False): {('composite', False),
                                              ('even', False),
                                              ('integer', False),
                                              ('odd', False), ('prime', False),
                                              ('rational', False),
                                              ('zero', False)},
                       ('algebraic', True): {('commutative', True),
                                             ('complex', True),
                                             ('finite', True),
                                             ('infinite', False),
                                             ('transcendental', False)},
                       ('antihermitian', False): {('imaginary', False)},
                       ('commutative', False): {('algebraic', False),
                                                ('complex', False),
                                                ('composite', False),
                                                ('even', False),
                                                ('extended_negative', False),
                                                ('extended_nonnegative', False),
                                                ('extended_nonpositive', False),
                                                ('extended_nonzero', False),
                                                ('extended_positive', False),
                                                ('extended_real', False),
                                                ('imaginary', False),
                                                ('integer', False),
                                                ('irrational', False),
                                                ('negative', False),
                                                ('noninteger', False),
                                                ('nonnegative', False),
                                                ('nonpositive', False),
                                                ('nonzero', False),
                                                ('odd', False),
                                                ('positive', False),
                                                ('prime', False),
                                                ('rational', False),
                                                ('real', False),
                                                ('transcendental', False),
                                                ('zero', False)},
                       ('complex', False): {('algebraic', False),
                                            ('composite', False),
                                            ('even', False),
                                            ('imaginary', False),
                                            ('integer', False),
                                            ('irrational', False),
                                            ('negative', False),
                                            ('nonnegative', False),
                                            ('nonpositive', False),
                                            ('nonzero', False), ('odd', False),
                                            ('positive', False),
                                            ('prime', False),
                                            ('rational', False),
                                            ('real', False),
                                            ('transcendental', False),
                                            ('zero', False)},
                       ('complex', True): {('commutative', True),
                                           ('finite', True),
                                           ('infinite', False)},
                       ('composite', False): set(),
                       ('composite', True): {('algebraic', True),
                                             ('commutative', True),
                                             ('complex', True),
                                             ('extended_negative', False),
                                             ('extended_nonnegative', True),
                                             ('extended_nonpositive', False),
                                             ('extended_nonzero', True),
                                             ('extended_positive', True),
                                             ('extended_real', True),
                                             ('finite', True),
                                             ('hermitian', True),
                                             ('imaginary', False),
                                             ('infinite', False),
                                             ('integer', True),
                                             ('irrational', False),
                                             ('negative', False),
                                             ('noninteger', False),
                                             ('nonnegative', True),
                                             ('nonpositive', False),
                                             ('nonzero', True),
                                             ('positive', True),
                                             ('prime', False),
                                             ('rational', True), ('real', True),
                                             ('transcendental', False),
                                             ('zero', False)},
                       ('even', False): {('zero', False)},
                       ('even', True): {('algebraic', True),
                                        ('commutative', True),
                                        ('complex', True),
                                        ('extended_real', True),
                                        ('finite', True), ('hermitian', True),
                                        ('imaginary', False),
                                        ('infinite', False), ('integer', True),
                                        ('irrational', False),
                                        ('noninteger', False), ('odd', False),
                                        ('rational', True), ('real', True),
                                        ('transcendental', False)},
                       ('extended_negative', False): {('negative', False)},
                       ('extended_negative', True): {('commutative', True),
                                                     ('composite', False),
                                                     ('extended_nonnegative',
                                                      False),
                                                     ('extended_nonpositive',
                                                      True),
                                                     ('extended_nonzero', True),
                                                     ('extended_positive',
                                                      False),
                                                     ('extended_real', True),
                                                     ('imaginary', False),
                                                     ('nonnegative', False),
                                                     ('positive', False),
                                                     ('prime', False),
                                                     ('zero', False)},
                       ('extended_nonnegative', False): {('composite', False),
                                                         ('extended_positive',
                                                          False),
                                                         ('nonnegative', False),
                                                         ('positive', False),
                                                         ('prime', False),
                                                         ('zero', False)},
                       ('extended_nonnegative', True): {('commutative', True),
                                                        ('extended_negative',
                                                         False),
                                                        ('extended_real', True),
                                                        ('imaginary', False),
                                                        ('negative', False)},
                       ('extended_nonpositive', False): {('extended_negative',
                                                          False),
                                                         ('negative', False),
                                                         ('nonpositive', False),
                                                         ('zero', False)},
                       ('extended_nonpositive', True): {('commutative', True),
                                                        ('composite', False),
                                                        ('extended_positive',
                                                         False),
                                                        ('extended_real', True),
                                                        ('imaginary', False),
                                                        ('positive', False),
                                                        ('prime', False)},
                       ('extended_nonzero', False): {('composite', False),
                                                     ('extended_negative',
                                                      False),
                                                     ('extended_positive',
                                                      False),
                                                     ('negative', False),
                                                     ('nonzero', False),
                                                     ('positive', False),
                                                     ('prime', False)},
                       ('extended_nonzero', True): {('commutative', True),
                                                    ('extended_real', True),
                                                    ('imaginary', False),
                                                    ('zero', False)},
                       ('extended_positive', False): {('composite', False),
                                                      ('positive', False),
                                                      ('prime', False)},
                       ('extended_positive', True): {('commutative', True),
                                                     ('extended_negative',
                                                      False),
                                                     ('extended_nonnegative',
                                                      True),
                                                     ('extended_nonpositive',
                                                      False),
                                                     ('extended_nonzero', True),
                                                     ('extended_real', True),
                                                     ('imaginary', False),
                                                     ('negative', False),
                                                     ('nonpositive', False),
                                                     ('zero', False)},
                       ('extended_real', False): {('composite', False),
                                                  ('even', False),
                                                  ('extended_negative', False),
                                                  ('extended_nonnegative',
                                                   False),
                                                  ('extended_nonpositive',
                                                   False),
                                                  ('extended_nonzero', False),
                                                  ('extended_positive', False),
                                                  ('integer', False),
                                                  ('irrational', False),
                                                  ('negative', False),
                                                  ('noninteger', False),
                                                  ('nonnegative', False),
                                                  ('nonpositive', False),
                                                  ('nonzero', False),
                                                  ('odd', False),
                                                  ('positive', False),
                                                  ('prime', False),
                                                  ('rational', False),
                                                  ('real', False),
                                                  ('zero', False)},
                       ('extended_real', True): {('commutative', True),
                                                 ('imaginary', False)},
                       ('finite', False): {('algebraic', False),
                                           ('complex', False),
                                           ('composite', False),
                                           ('even', False),
                                           ('imaginary', False),
                                           ('infinite', True),
                                           ('integer', False),
                                           ('irrational', False),
                                           ('negative', False),
                                           ('nonnegative', False),
                                           ('nonpositive', False),
                                           ('nonzero', False), ('odd', False),
                                           ('positive', False),
                                           ('prime', False),
                                           ('rational', False), ('real', False),
                                           ('transcendental', False),
                                           ('zero', False)},
                       ('finite', True): {('infinite', False)},
                       ('hermitian', False): {('composite', False),
                                              ('even', False),
                                              ('integer', False),
                                              ('irrational', False),
                                              ('negative', False),
                                              ('nonnegative', False),
                                              ('nonpositive', False),
                                              ('nonzero', False),
                                              ('odd', False),
                                              ('positive', False),
                                              ('prime', False),
                                              ('rational', False),
                                              ('real', False),
                                              ('zero', False)},
                       ('imaginary', True): {('antihermitian', True),
                                             ('commutative', True),
                                             ('complex', True),
                                             ('composite', False),
                                             ('even', False),
                                             ('extended_negative', False),
                                             ('extended_nonnegative', False),
                                             ('extended_nonpositive', False),
                                             ('extended_nonzero', False),
                                             ('extended_positive', False),
                                             ('extended_real', False),
                                             ('finite', True),
                                             ('infinite', False),
                                             ('integer', False),
                                             ('irrational', False),
                                             ('negative', False),
                                             ('noninteger', False),
                                             ('nonnegative', False),
                                             ('nonpositive', False),
                                             ('nonzero', False), ('odd', False),
                                             ('positive', False),
                                             ('prime', False),
                                             ('rational', False),
                                             ('real', False), ('zero', False)},
                       ('infinite', False): {('finite', True)},
                       ('infinite', True): {('algebraic', False),
                                            ('complex', False),
                                            ('composite', False),
                                            ('even', False), ('finite', False),
                                            ('imaginary', False),
                                            ('integer', False),
                                            ('irrational', False),
                                            ('negative', False),
                                            ('nonnegative', False),
                                            ('nonpositive', False),
                                            ('nonzero', False), ('odd', False),
                                            ('positive', False),
                                            ('prime', False),
                                            ('rational', False),
                                            ('real', False),
                                            ('transcendental', False),
                                            ('zero', False)},
                       ('integer', False): {('composite', False),
                                            ('even', False), ('odd', False),
                                            ('prime', False), ('zero', False)},
                       ('integer', True): {('algebraic', True),
                                           ('commutative', True),
                                           ('complex', True),
                                           ('extended_real', True),
                                           ('finite', True),
                                           ('hermitian', True),
                                           ('imaginary', False),
                                           ('infinite', False),
                                           ('irrational', False),
                                           ('noninteger', False),
                                           ('rational', True), ('real', True),
                                           ('transcendental', False)},
                       ('irrational', True): {('commutative', True),
                                              ('complex', True),
                                              ('composite', False),
                                              ('even', False),
                                              ('extended_nonzero', True),
                                              ('extended_real', True),
                                              ('finite', True),
                                              ('hermitian', True),
                                              ('imaginary', False),
                                              ('infinite', False),
                                              ('integer', False),
                                              ('noninteger', True),
                                              ('nonzero', True), ('odd', False),
                                              ('prime', False),
                                              ('rational', False),
                                              ('real', True), ('zero', False)},
                       ('negative', False): set(),
                       ('negative', True): {('commutative', True),
                                            ('complex', True),
                                            ('composite', False),
                                            ('extended_negative', True),
                                            ('extended_nonnegative', False),
                                            ('extended_nonpositive', True),
                                            ('extended_nonzero', True),
                                            ('extended_positive', False),
                                            ('extended_real', True),
                                            ('finite', True),
                                            ('hermitian', True),
                                            ('imaginary', False),
                                            ('infinite', False),
                                            ('nonnegative', False),
                                            ('nonpositive', True),
                                            ('nonzero', True),
                                            ('positive', False),
                                            ('prime', False), ('real', True),
                                            ('zero', False)},
                       ('noninteger', True): {('commutative', True),
                                              ('composite', False),
                                              ('even', False),
                                              ('extended_nonzero', True),
                                              ('extended_real', True),
                                              ('imaginary', False),
                                              ('integer', False),
                                              ('odd', False), ('prime', False),
                                              ('zero', False)},
                       ('nonnegative', False): {('composite', False),
                                                ('positive', False),
                                                ('prime', False),
                                                ('zero', False)},
                       ('nonnegative', True): {('commutative', True),
                                               ('complex', True),
                                               ('extended_negative', False),
                                               ('extended_nonnegative', True),
                                               ('extended_real', True),
                                               ('finite', True),
                                               ('hermitian', True),
                                               ('imaginary', False),
                                               ('infinite', False),
                                               ('negative', False),
                                               ('real', True)},
                       ('nonpositive', False): {('negative', False),
                                                ('zero', False)},
                       ('nonpositive', True): {('commutative', True),
                                               ('complex', True),
                                               ('composite', False),
                                               ('extended_nonpositive', True),
                                               ('extended_positive', False),
                                               ('extended_real', True),
                                               ('finite', True),
                                               ('hermitian', True),
                                               ('imaginary', False),
                                               ('infinite', False),
                                               ('positive', False),
                                               ('prime', False),
                                               ('real', True)},
                       ('nonzero', False): {('composite', False),
                                            ('negative', False),
                                            ('positive', False),
                                            ('prime', False)},
                       ('nonzero', True): {('commutative', True),
                                           ('complex', True),
                                           ('extended_nonzero', True),
                                           ('extended_real', True),
                                           ('finite', True),
                                           ('hermitian', True),
                                           ('imaginary', False),
                                           ('infinite', False), ('real', True),
                                           ('zero', False)},
                       ('odd', False): set(),
                       ('odd', True): {('algebraic', True),
                                       ('commutative', True), ('complex', True),
                                       ('even', False),
                                       ('extended_nonzero', True),
                                       ('extended_real', True),
                                       ('finite', True), ('hermitian', True),
                                       ('imaginary', False),
                                       ('infinite', False), ('integer', True),
                                       ('irrational', False),
                                       ('noninteger', False), ('nonzero', True),
                                       ('rational', True), ('real', True),
                                       ('transcendental', False),
                                       ('zero', False)},
                       ('positive', False): {('composite', False),
                                             ('prime', False)},
                       ('positive', True): {('commutative', True),
                                            ('complex', True),
                                            ('extended_negative', False),
                                            ('extended_nonnegative', True),
                                            ('extended_nonpositive', False),
                                            ('extended_nonzero', True),
                                            ('extended_positive', True),
                                            ('extended_real', True),
                                            ('finite', True),
                                            ('hermitian', True),
                                            ('imaginary', False),
                                            ('infinite', False),
                                            ('negative', False),
                                            ('nonnegative', True),
                                            ('nonpositive', False),
                                            ('nonzero', True), ('real', True),
                                            ('zero', False)},
                       ('prime', False): set(),
                       ('prime', True): {('algebraic', True),
                                         ('commutative', True),
                                         ('complex', True),
                                         ('composite', False),
                                         ('extended_negative', False),
                                         ('extended_nonnegative', True),
                                         ('extended_nonpositive', False),
                                         ('extended_nonzero', True),
                                         ('extended_positive', True),
                                         ('extended_real', True),
                                         ('finite', True), ('hermitian', True),
                                         ('imaginary', False),
                                         ('infinite', False), ('integer', True),
                                         ('irrational', False),
                                         ('negative', False),
                                         ('noninteger', False),
                                         ('nonnegative', True),
                                         ('nonpositive', False),
                                         ('nonzero', True), ('positive', True),
                                         ('rational', True), ('real', True),
                                         ('transcendental', False),
                                         ('zero', False)},
                       ('rational', False): {('composite', False),
                                             ('even', False),
                                             ('integer', False), ('odd', False),
                                             ('prime', False),
                                             ('zero', False)},
                       ('rational', True): {('algebraic', True),
                                            ('commutative', True),
                                            ('complex', True),
                                            ('extended_real', True),
                                            ('finite', True),
                                            ('hermitian', True),
                                            ('imaginary', False),
                                            ('infinite', False),
                                            ('irrational', False),
                                            ('real', True),
                                            ('transcendental', False)},
                       ('real', False): {('composite', False), ('even', False),
                                         ('integer', False),
                                         ('irrational', False),
                                         ('negative', False),
                                         ('nonnegative', False),
                                         ('nonpositive', False),
                                         ('nonzero', False), ('odd', False),
                                         ('positive', False), ('prime', False),
                                         ('rational', False), ('zero', False)},
                       ('real', True): {('commutative', True),
                                        ('complex', True),
                                        ('extended_real', True),
                                        ('finite', True), ('hermitian', True),
                                        ('imaginary', False),
                                        ('infinite', False)},
                       ('transcendental', True): {('algebraic', False),
                                                  ('commutative', True),
                                                  ('complex', True),
                                                  ('composite', False),
                                                  ('even', False),
                                                  ('finite', True),
                                                  ('infinite', False),
                                                  ('integer', False),
                                                  ('odd', False),
                                                  ('prime', False),
                                                  ('rational', False),
                                                  ('zero', False)},
                       ('zero', False): set(),
                       ('zero', True): {('algebraic', True),
                                        ('commutative', True),
                                        ('complex', True), ('composite', False),
                                        ('even', True),
                                        ('extended_negative', False),
                                        ('extended_nonnegative', True),
                                        ('extended_nonpositive', True),
                                        ('extended_nonzero', False),
                                        ('extended_positive', False),
                                        ('extended_real', True),
                                        ('finite', True), ('hermitian', True),
                                        ('imaginary', False),
                                        ('infinite', False), ('integer', True),
                                        ('irrational', False),
                                        ('negative', False),
                                        ('noninteger', False),
                                        ('nonnegative', True),
                                        ('nonpositive', True),
                                        ('nonzero', False), ('odd', False),
                                        ('positive', False), ('prime', False),
                                        ('rational', True), ('real', True),
                                        ('transcendental', False)}},
 'prereq': {'algebraic': {'commutative', 'complex', 'composite', 'even',
                          'finite', 'infinite', 'integer', 'odd', 'prime',
                          'rational', 'transcendental', 'zero'},
            'antihermitian': {'imaginary'},
            'commutative': {'algebraic', 'complex', 'composite', 'even',
                            'extended_negative', 'extended_nonnegative',
                            'extended_nonpositive', 'extended_nonzero',
                            'extended_positive', 'extended_real', 'imaginary',
                            'integer', 'irrational', 'negative', 'noninteger',
                            'nonnegative', 'nonpositive', 'nonzero', 'odd',
                            'positive', 'prime', 'rational', 'real',
                            'transcendental', 'zero'},
            'complex': {'algebraic', 'commutative', 'composite', 'even',
                        'finite', 'imaginary', 'infinite', 'integer',
                        'irrational', 'negative', 'nonnegative', 'nonpositive',
                        'nonzero', 'odd', 'positive', 'prime', 'rational',
                        'real', 'transcendental', 'zero'},
            'composite': {'algebraic', 'commutative', 'complex',
                          'extended_negative', 'extended_nonnegative',
                          'extended_nonpositive', 'extended_nonzero',
                          'extended_positive', 'extended_real', 'finite',
                          'hermitian', 'imaginary', 'infinite', 'integer',
                          'irrational', 'negative', 'noninteger', 'nonnegative',
                          'nonpositive', 'nonzero', 'positive', 'prime',
                          'rational', 'real', 'transcendental', 'zero'},
            'even': {'algebraic', 'commutative', 'complex', 'extended_real',
                     'finite', 'hermitian', 'imaginary', 'infinite', 'integer',
                     'irrational', 'noninteger', 'odd', 'rational', 'real',
                     'transcendental', 'zero'},
            'extended_negative': {'commutative', 'composite',
                                  'extended_nonnegative',
                                  'extended_nonpositive', 'extended_nonzero',
                                  'extended_positive', 'extended_real',
                                  'imaginary', 'negative', 'nonnegative',
                                  'positive', 'prime', 'zero'},
            'extended_nonnegative': {'commutative', 'composite',
                                     'extended_negative', 'extended_positive',
                                     'extended_real', 'imaginary', 'negative',
                                     'nonnegative', 'positive', 'prime',
                                     'zero'},
            'extended_nonpositive': {'commutative', 'composite',
                                     'extended_negative', 'extended_positive',
                                     'extended_real', 'imaginary', 'negative',
                                     'nonpositive', 'positive', 'prime',
                                     'zero'},
            'extended_nonzero': {'commutative', 'composite',
                                 'extended_negative', 'extended_positive',
                                 'extended_real', 'imaginary', 'irrational',
                                 'negative', 'noninteger', 'nonzero', 'odd',
                                 'positive', 'prime', 'zero'},
            'extended_positive': {'commutative', 'composite',
                                  'extended_negative', 'extended_nonnegative',
                                  'extended_nonpositive', 'extended_nonzero',
                                  'extended_real', 'imaginary', 'negative',
                                  'nonpositive', 'positive', 'prime', 'zero'},
            'extended_real': {'commutative', 'composite', 'even',
                              'extended_negative', 'extended_nonnegative',
                              'extended_nonpositive', 'extended_nonzero',
                              'extended_positive', 'imaginary', 'integer',
                              'irrational', 'negative', 'noninteger',
                              'nonnegative', 'nonpositive', 'nonzero', 'odd',
                              'positive', 'prime', 'rational', 'real', 'zero'},
            'finite': {'algebraic', 'complex', 'composite', 'even', 'imaginary',
                       'infinite', 'integer', 'irrational', 'negative',
                       'nonnegative', 'nonpositive', 'nonzero', 'odd',
                       'positive', 'prime', 'rational', 'real',
                       'transcendental', 'zero'},
            'hermitian': {'composite', 'even', 'integer', 'irrational',
                          'negative', 'nonnegative', 'nonpositive', 'nonzero',
                          'odd', 'positive', 'prime', 'rational', 'real',
                          'zero'},
            'imaginary': {'antihermitian', 'commutative', 'complex',
                          'composite', 'even', 'extended_negative',
                          'extended_nonnegative', 'extended_nonpositive',
                          'extended_nonzero', 'extended_positive',
                          'extended_real', 'finite', 'infinite', 'integer',
                          'irrational', 'negative', 'noninteger', 'nonnegative',
                          'nonpositive', 'nonzero', 'odd', 'positive', 'prime',
                          'rational', 'real', 'zero'},
            'infinite': {'algebraic', 'complex', 'composite', 'even', 'finite',
                         'imaginary', 'integer', 'irrational', 'negative',
                         'nonnegative', 'nonpositive', 'nonzero', 'odd',
                         'positive', 'prime', 'rational', 'real',
                         'transcendental', 'zero'},
            'integer': {'algebraic', 'commutative', 'complex', 'composite',
                        'even', 'extended_real', 'finite', 'hermitian',
                        'imaginary', 'infinite', 'irrational', 'noninteger',
                        'odd', 'prime', 'rational', 'real', 'transcendental',
                        'zero'},
            'irrational': {'commutative', 'complex', 'composite', 'even',
                           'extended_real', 'finite', 'hermitian', 'imaginary',
                           'infinite', 'integer', 'odd', 'prime', 'rational',
                           'real', 'zero'},
            'negative': {'commutative', 'complex', 'composite',
                         'extended_negative', 'extended_nonnegative',
                         'extended_nonpositive', 'extended_nonzero',
                         'extended_positive', 'extended_real', 'finite',
                         'hermitian', 'imaginary', 'infinite', 'nonnegative',
                         'nonpositive', 'nonzero', 'positive', 'prime', 'real',
                         'zero'},
            'noninteger': {'commutative', 'composite', 'even', 'extended_real',
                           'imaginary', 'integer', 'irrational', 'odd', 'prime',
                           'zero'},
            'nonnegative': {'commutative', 'complex', 'composite',
                            'extended_negative', 'extended_nonnegative',
                            'extended_real', 'finite', 'hermitian', 'imaginary',
                            'infinite', 'negative', 'positive', 'prime', 'real',
                            'zero'},
            'nonpositive': {'commutative', 'complex', 'composite',
                            'extended_nonpositive', 'extended_positive',
                            'extended_real', 'finite', 'hermitian', 'imaginary',
                            'infinite', 'negative', 'positive', 'prime', 'real',
                            'zero'},
            'nonzero': {'commutative', 'complex', 'composite',
                        'extended_nonzero', 'extended_real', 'finite',
                        'hermitian', 'imaginary', 'infinite', 'irrational',
                        'negative', 'odd', 'positive', 'prime', 'real',
                        'zero'},
            'odd': {'algebraic', 'commutative', 'complex', 'even',
                    'extended_real', 'finite', 'hermitian', 'imaginary',
                    'infinite', 'integer', 'irrational', 'noninteger',
                    'rational', 'real', 'transcendental', 'zero'},
            'positive': {'commutative', 'complex', 'composite',
                         'extended_negative', 'extended_nonnegative',
                         'extended_nonpositive', 'extended_nonzero',
                         'extended_positive', 'extended_real', 'finite',
                         'hermitian', 'imaginary', 'infinite', 'negative',
                         'nonnegative', 'nonpositive', 'nonzero', 'prime',
                         'real', 'zero'},
            'prime': {'algebraic', 'commutative', 'complex', 'composite',
                      'extended_negative', 'extended_nonnegative',
                      'extended_nonpositive', 'extended_nonzero',
                      'extended_positive', 'extended_real', 'finite',
                      'hermitian', 'imaginary', 'infinite', 'integer',
                      'irrational', 'negative', 'noninteger', 'nonnegative',
                      'nonpositive', 'nonzero', 'positive', 'rational', 'real',
                      'transcendental', 'zero'},
            'rational': {'algebraic', 'commutative', 'complex', 'composite',
                         'even', 'extended_real', 'finite', 'hermitian',
                         'imaginary', 'infinite', 'integer', 'irrational',
                         'odd', 'prime', 'real', 'transcendental', 'zero'},
            'real': {'commutative', 'complex', 'composite', 'even',
                     'extended_real', 'finite', 'hermitian', 'imaginary',
                     'infinite', 'integer', 'irrational', 'negative',
                     'nonnegative', 'nonpositive', 'nonzero', 'odd', 'positive',
                     'prime', 'rational', 'zero'},
            'transcendental': {'algebraic', 'commutative', 'complex',
                               'composite', 'even', 'finite', 'infinite',
                               'integer', 'odd', 'prime', 'rational', 'zero'},
            'zero': {'algebraic', 'commutative', 'complex', 'composite', 'even',
                     'extended_negative', 'extended_nonnegative',
                     'extended_nonpositive', 'extended_nonzero',
                     'extended_positive', 'extended_real', 'finite',
                     'hermitian', 'imaginary', 'infinite', 'integer',
                     'irrational', 'negative', 'noninteger', 'nonnegative',
                     'nonpositive', 'nonzero', 'odd', 'positive', 'prime',
                     'rational', 'real', 'transcendental'}}}
