# ------------------------------------------------------------------ #
#                                                                    #
#              SymPy CI script for Github Actions                    #
#                                                                    #
#  Upload a nightly wheel to the Anaconda scientific-python channel  #
#                                                                    #
#         https://scientific-python.org/specs/spec-0004/             #
#                                                                    #
# ------------------------------------------------------------------ #

name: nightly-wheel-upload
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  nightly-wheel:
    name: Build Nightly Wheel
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'
      - run: python -m pip install --upgrade pip build
      - run: python -m build --wheel

      - name: Upload built wheel
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: nightly-wheel-dist
          path: dist
          if-no-files-found: error

  # Keep this job separate from the nightly-wheel job to limit exposure to the
  # secrets.
  nightly-wheel-upload:
    name: Upload Nightly Wheel
    needs: nightly-wheel
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Download built wheel
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: nightly-wheel-dist
          path: dist

      - name: Upload wheel
        uses: scientific-python/upload-nightly-action@5748273c71e2d8d3a61f3a11a16421c8954f9ecf # 0.6.3
        with:
          artifacts_path: dist
          # This token is generated from anaconda.org
          # https://github.com/scientific-python/upload-nightly-action/issues/111
          anaconda_nightly_upload_token: ${{ secrets.ANACONDA_ORG_UPLOAD_TOKEN }} # zizmor: ignore[secrets-outside-env]
